# Go Ye!  Matt. 28, 19
## The Divine Commission. {-}

It is God's perogative to have people come to Him, and His invitation is extended to all men in a serious, efficacious call.

"Come unto Me, all ye that labor and are heavy laden, and I will give you rest!"  Matt. 11, 28.

"Look unto Me and be ye saved, all the ends of the earth."  Is. 45, 22.

"Come, for all things are now ready."  Luke 14, 17.

"And the Spirit and the bride say, Come!  And let him that heareth say, Come!  And let him that is athirst come.  And whosoever will, let him take the water of life freely."  Rev. 22, 17.

But to make known this glorious intention and invitation to men _God has commissioned His children_, the believers, throughout the world.  They are to be His representatives; they are to be His messengers, His ambassadors; they are to be His agents in making known His call of salvation, in inviting men to the feast of His love and grace.

Even in Old Testament times this was true.  To His Zion, to the members of His Church under the Old Dispensation, the Lord calls out: --

"O Zion, that bringest good tidings, get thee up into a high mountain!  O Jerusalem, that bringest good tidings, lift up thy voice with strength; lift it up, be not afraid; say unto the cities of Judah, Behold your God!"  Is. 40, 9.

But still more direct, still more unmistakable and powerful, is the Lord's commission to the New Testament Church and to all its members: --

"GO YE THEREFORE AND TEACH ALL NATIONS; BAPTIZING THEM IN THE NAME OF THE FATHER AND OF THE SON AND OF THE HOLY GHOST; TEACHING THEM TO OBSERVE ALL THINGS WHATSOEVER I HAVE COMMANDED YOU."  Matt. 28, 19. 20.

"Go ye!" He says.

"Bring My sons from far and My daughters from the ends of the earth!"  Is. 43, 6.

"Ye shall be witnesses unto Me both in Jerusalem, and in all Judea, and in Samaria, and unto the uttermost part of the earth."  Acts 1, 8.

It is not enough that we build churches and chapels and have free pews for all who desire to come; it is not enough that we erect bulletin-boards and announcement-boards in front of our churches, at street intersections, and in other public places; it is not enough that we publish parish-papers and pulpit programs; it is not enough that we advertise in the newspapers on Saturdays and upon all special occasions.  All this is good and laudable; all this means carrying out a part of the work which is ours to do; all this may reach souls that are in need of the message of salvation; all this may bring some into the fold.

"GO!" means _personal work_, if possible work in person, by direct personal contact; it means seeing that work is done and carrying out the work in person, if possible, or attending to its performance in person, if it must be done through others.

"Go ye also into the vineyard!" Matt 20, 4. 7.  That is the Lord's Commission.  It might be done by proxy, of course; but where does a person do his own work, which is entrusted to him, by proxy, unless it be, perhaps, under his own direct, personal supervision?

And there is more to be considered.  The Bridegroom, Christ, is sending His friends to win the bride, the believers, whom He wants with Him in the enjoyment of the eternal bliss of heaven.  St. Paul says of his own work in winning souls for Christ: --

"I have espoused you to one Husband that I may present you as a chaste virgin to Christ." 2 Cor. 11, 2.  And John the Baptist testified: --

"The Friend of the Bridegroom which standeth and heareth Him, rejoiceth greatly because of the Bridegroom's voice.  This my joy therefore is fulfilled." John 3, 29.  John, like Paul, did his work for Christ in person; he gained souls by personal work.  It is the way we ought to choose as we have opportunity and in accordance with the method of working set forth by God in His Holy Word.  

"Go YE!" says Christ.  The commission is not confined to the apostles.  They, indeed, are the teachers of the whole world until the end of time.  Through their word others are to believe on Jesus Christ, the Savior of the world.  John 17, 20.

"Go YE!" is not addressed to trained pastors and missionaries only, although to them is committed the task of public preaching.  It was a little servant girl, a slave whose name is not even mentioned in the Bible, who called the attention of Naaman's wife to the prophet of Jehovah in Israel.  2 Kings 5, 3.  It was the untrained fisherman, Andrew, who told his brother Simon about the Messiah, John 1, 41, and whose example was followed by Philip in speaking to Nathanel.  John 1, 45.

"Go ye INTO ALL THE WORLD!" is the Savior's commission.  The world is big and wide, and there are still more than twice as many without the knowledge of Christ as there are, even nominally, within the pale of the Church.  INto many of the heathen lands the messengers of the Gospel have gone.  Into some of the heathen lands some of our own messengers are gone -- alas! into all too few.  There never was a truer answer given than that turned in my a young Christian, the question being:  How many missionaries have we in India and China?  He said, with wonderful frankness:  "NOT ENOUGH!"

Yes, NOT ENOUGH!  We have not reached nearly all lands of the world.  We have made but a feeble, an all too feeble, beginning.

Somehow we do not seem to realize the misery of the untold millions that are "without God in the world."  Eph 2, 12.  Perhaps if they were living across the street from us and we had the picture of their misery and their idolatry and their vileness before our eyes every day, our hearts would be stirred to a greater effort in their behalf, and we might accomplish more in our foreign mission endeavor.

```
We smoothly speak of teeming masses, of millions still in darkest night;
We glibly pray that those in blindness be given spiritual sight;
We prate about our mission duty and of the missionary need:
But what would you do, and what would I do,
IF CHINA WERE ACROSS THE STREET?

We say that we are interested when now and then we hear a talk
Of how the heathen hosts are living and in the fiercest horrors walk,
How they are kept the truth from learning, their leaders empty husks them feed:
But what would you do, and what would I do,
IF INDIA WERE ACROSS THE STREET?

We feel that we have done our duty when we just sometimes give a mite,
When from the riches of our treasures we now and then deal out a bite;
We spend our billions for vain baubles, for luxuries we do not need:
But what would you do, and what would I do, 
WITH AFRICA ACROSS THE STREET?

***

Oh, may the love of Christ constrain us to see our mission duty through
That we be filled with burning fervor, that less we talk and more we do
That we no longer speak of burdens, but lift the misery untold
THAT ALL OUR LIFE BE SPENT IN BRINGING MORE SOULS INTO THE SAVIOR'S FOLD
```

It is absolutely necessary that we get this better viewpoint, that we begin to think of our missionary duty in terms of direct contact, that we visualize the spiritual needs of those who are still children of wrath without being conscious of that fact.

"INTO ALL THE WORLD!"  Not only the foreign countries, but also the home field, the country in which we live!

```
If you cannot cross the ocean
And the heathen lands explore,
You can find the heathen nearer,
You can help them at your door!
```

Ah, yes; millions of them, in the very midst of Christianity and civilization!

Do you know whether your nearest neighbors are members of a Christian Church?  Have you ever inquired whether the people across the street know anything about the Savior and the way of salvation?

Have you ever considered that thousands of us who are sitting at the full tables of God's riches in Christ Jesus as we have them in our dear Lutheran Church have done little or nothing to bring the Gospel of God's mercy to men and women and children in our own neighborhood?

```
Shall we, whose souls are lighted
With wisdom from on high,
Shall we to men benighted
The lamp of life deny?
```

Shall we do so by failing to make an earnest effort to reach them by _going_ and inviting them to partake in the riches earned also for them by Christ's atoning work?

"PREACH THE GOSPEL!"  That is the means committed to us for the winning of blood-bought souls, the means by which the grace of God is to be brought to the attention of men and to be made alive in their hearts.

Not the so-called Gospel of social service, of which we hear so much in our days; not the message of present-worldliness, with its cry of:  Save the people of this world!  It is true that the highest forms of social blessings have come to men with Christianity, and that pracitcally every real advance in the world in the last nineteen centuries proceeded from Christianity or is connected with the Christian religion.  But that is the effect of the soul-changing power of the Gospel of Christ, a power which is so great that it influences not only those who actually confess Christianity and live in accordance with its high ideals, but that it exerts a purging and a beautifying impulse also on others who come in contact with its monuments.

The Gospel which we are to bring to men is a power of God unto salvation because it is the message of the free grace and mercy of God in Christ Jesus, the one and only Savior of mankind, who in our stead and for our redemption came down from heaven, was incarnate of the Holy Ghost by the Virgin Mary, and gave His life as a ransom for mankind when He died on the cross.  It is the message of the forgiveness of sins for the skae of Jesus that is the essence of the gospel.  And it is the Gospel which we are bending our efforts to bring to all men everywhere.

"TO EVERY CREATURE," "TO ALL NATIONS!"  To every member of this lost and condemned mankind!  To rich and poor, to old and young, to the socially prominent and to the outcast of human society, to the capitalist and to the workingman -- to _all_ men this message is to be brought.

"God will have _all_ men to be saved and to come unto the knowledge of the truth."  1 Tim. 2, 4.

Having made disciples of men wherever we find them, in palace and in hovel, and having brought them to Christ by the Sacrament of Baptism, we are to extend our initial work by teaching them to observe all things whatsoever He has commanded us.  There is no end, no limit, to the possibilities of our evangelistic work on this side of the grave.  The more we work, the greater are the possibilities and the greater the opportunities for service.

Do you know what place such soul-winning has in the eyes of God?

The whole machinery of redemption was set in motion by Him because of it.  Even in the Old Testament He says, time and again, that He is the Savior of His people.

"God, their Savior, which had done great things in Egypt."  Ps. 106, 21.

"I am the Lord, thy God, the Holy One of Israel, thy Savior."  Is 43, 4.

"There is no God else beside Me, a just God and a Savior; there is none beside Me."  Is. 45, 21.

"All Flesh shall know that I, the Lord, am thy Savior and thy Redeemer, the Mighty One of Jacob."  Is. 49, 26.

"Thou shalt know that I, the Lord, am thy Savior and thy Redeemer."  Is. 60, 16.

"For He said, Surely they are My people, children that will not lie:  so He was their Savior."  Is. 63, 8.

And has not the New Testament fully borne out the promise and the prophecy of the Old?  Is not the thought of the salvation of makind on the basis of the love and mercy of God the central theme in every book given to men in the New Dispensation?  

"My spirit hath rejoiced in God, my Savior."  Luke 1, 47.

"Paul, an apostle of Jesus Christ by the commandment of God, our Savior, and Lord Jesus Christ, which is our Hope."  1 Tim. 1, 1.

"We trust in the living God, who is the Savior of all men."  1 Tim. 4, 10.

"God hath in due times manifested His Word through preaching, which is committed unto me according to the commandment of God, our Savior."  Titus 1, 3.

"That they may adorn the doctrine of God, our Savior, in all things."  Titus 2, 10.

"To the only wise God, our Savior, be glory and majesty, dominion and power, both now and Forever!"  Jude 25.

Do you want further evidence of the Importance of soul-winning as God sees it?  Not only does His own name indicate His desire for the salvation of men, but He also states it in words of unmistakable emphasis.

"Have I any pleasure at all that the wicked should die? saith the Lord God, and not that he should return from his ways and live?"  Ezek. 18, 23.

"God will have all men to be saved, and to come unto the knowledge of truth."  1 Tim. 2, 4.

"The Lord is not willing that any should perish, but that all should come to repentance."  2 Pet. 3, 9.

Do you still need more information to convince you of the interest that God takes in saving men from their sins?  Can there be a greater proof than that He sent His only-begotten Son, Jesus Christ, to accomplish the salvation of all mankind?

"We have seen and do testify that the Father sent the Son to be the Savior of the world."  1 John 4, 14.

"When the fulness of the time was come, God sent forth His Son, made of a woman, made under the Law, to redeem them that were under the Law."  Gal. 4, 4.

"God so loved the world that He gave His only-begotten Son, that whosoever believeth in Him should not perish, but have everlasting life."  John 3, 16.

Is it a wonder, with such facts from the Bible before them, that some of the foremost workers for Christ felt constrained to go and measure up, in some degree, to the expectatino of God?

It was Carey who declared that we must "expect great things from God," and that we must "attempt great things for God," and who in the strength of Is. 54, 2. 3 set out for India.  

It was Allen Gardiner who gave up all prospects of becoming wealthy in order to go to the darkest part of South America, Tierra del Fuego, and to lay down his life with the words before his eyes:  "My soul, wait thou only upon God; for my expectation is from Him."  Ps. 62, 58.

It was David Livingstone who refused to abandon his task after Stanley had found him, but resolutely sent the younger man home with the precious records of work already accomplished, while he turned back to finish alone his great undertaking.

It was Mary Slessor, of Calabar, who left the very coast which served as a station of communication with far-away England and went into the interior to each more of those people, who reverently called her "Ma," the Gospel of salvation.

It was Theodore Fliedner who did not shrink from a discharged female conflict, but with this woman as the first inmate of his improvised home began the work which resulted in the revival of the female diaconate.  

It was John Geddie who went to Aneityum, laboring there with such success that the native Christians themselves said of him, "When he landed in 1848, there were no Christians here; when he left, in 1872, there were no heathen."

It was Brainerd who declared, "I cared not where or how I lived or what hardships I went through, so that I could but gain souls for Christ."

It was Gregory who stated, "OF all the sacrifices there is none in the sight of Almighty God equal to zeal for souls."

```
"Go ye unto ev'ry nation!"
Is the Savior's great command;
"Preach he Gospel of salvation
To all men in ev'ry land;
Teach them all the glorious message
That I died to end all strife
And that death might be the passage
To the blissful endless life."

'Tis by Jesus' love and merit
All men are at peace with God,
Reassured by His free Spirit,
Saved from all their guilty load.
He who trusts in Christ his Savior,
Who for all men did atone,
Will receive the Father's favor,
Will be saved by grace alone.

To the nations most enlightened
With this world's progressive lore,
And to those whose souls are frightened,
Bound by superstitious lore;
Those whose god is this world's mammon
And those deep in poverty,
To the rich and the street gamin,
Comes the call to make them free.

Let us shout it full of gladness
Wheresoever men we find;
Let us drive away all sadness,
Grief of heart and care of mine;
Let us tell the wondrous story
Of the marvel of God's love,
Let us magnify His Glory
Till the hardest hearts we move;

Till all men of ev'ry station
Rich and poor and young and old;
Till all men of ev'ry nation
May be brought into the fold;
Till the Savior's robe of beauty
Covers ev'ry guilty stain;
Till they know their highest duty
Everlasting life to gain.
```

Would you know the motive which prompts such a response in the hearts of Christians everywhere? -- You will find more on this point in the next chapters.


