# I Delight to Do Thy Will!  Is. 40, 8
## The obligation of Love. {-}

The divine commission is not an arbitrary command; it is not a legal precept issued by God by virtue of His majesty and power.  It is, as a matter of fact, addressed to Christians and would have no meaning for anyone else.  Only he can understand this commission and properly act upon it in whose heart the Holy Ghost has already wrought a knowledge of the salvation brought by Christ and revealed in His Word.  It is a heart of this kind that is actuated by the obligation of love resting upon it.

And how can it be otherwise, since the Christina continually has before his eyes the wonderful picture of Christ and the manner in which He carried out and satisfied the obligation of love resting upon Him by virtue of His own choice?

For what was the guiding principle of His life and work?

"THEN SAID I, LO, I COME; IN THE VOLUME OF THE BOOK IT IS WRITTEN OF ME.  I DELIGHT TO DO THY WILL, O MY GOD."  Ps. 40, 8.

These are words of the Messiah, as the writer to the Hebrews, chap. 10, 5-7, shows.  The Son of God had from eternity taken part in the counsel of God pertaining to fallen mankind, and He had declared His willingness to work the redemption, which none but He could accomplish.  This attitude is evident throughout our Savior's life.

"Wist ye not that I _must_ be about My Father's business?" was the half-reproachful question which He addressed to His parents when He was taken to the festival of the Passover at the age of twelve years.  Luke 2, 49.

"I _must_ walk to-day and to-morrow and the day following."  Luke 13, 33.

"I _must_ work the works of Him that sent Me while it is day; the night cometh when no man can work."  John 9, 4.

"From that time forth began Jesus to show unto His disciples how that He _must_ go unto Jerusalem, and suffer many things of the elders and chief priests and scribes, and be killed, and be raised again the third day."  Matt. 16, 21.

"For I say unto you that this that is written _must_ yet be accomplished in Me, And He was reckoned among the transgressors."  Luke 22, 37.

"Thinkest thou that I cannot now pray to My Father, and He shall presently give Me more than twleve legions of angels?  But how then shall Scriptures be fulfilled that it _must_ be?"  Matt. 26, 53-54.

"Remember how He spake unto you when he was yet in Galilee, saying, The Son of Man _must_ be delivered into the hands of sinful men and be crucified and the third day rise again."  Luke 24, 7.

"_Ought_ not Christ to havve suffered these things and to enter into His glory?"  Luke 24, 26.

"And He said unto them, Thus it is written, and thus _it behooved Christ_ to suffer and to rise from the dead the third day."  Luke 24, 46.

Thus we find it all the way through the life of Christ, -- the "must" of the divine obligation resting upon Him.  He has placed Himself at the disposal of God, and in line with His own eternal will, which is at all times in perfect agreement with that of the Father, John 5, 19, He carried out the plan of redemption.

What the German hymn-writer Paul Gerhardt has the Savior say is true: --

|	 Yea, Father, yea most willingly
|	 I'll bear what Thou commandest;
|	 My will conforms to Thy decree,
|	 I do what Thou demandest.--
|	 O wondrous Love, what has Thou done!
|	 The Father offers up his Son,
|	 The Son, content, descendeth!
|	 O Love, O Love, how strong art Thou!
|	 In shroud and grave Thou lay'st Him low
|	 Whose word the mountains rendeth!

Where would we and all mankind be if the Savior had wavered in His divine determination, if He had faltered and shrunk at sight of the cross on which His tortured body was to be suspended?!  What an immeasurable burden of gratitude is laid upon us by virtue of His unflinching persistence in the obedience prompted by His redemptive love!

Are you looking for still further evidence regarding the position which soul-winning has in the mind of Christ, the one and only Savior of mankind?  Consider the place it has in His life and work.  Remember that His very name indicates the purpose of His life and work; for Jesus means "Redeemer, Savior."  Matt. 1, 21.

It is the name given to our Lord throughout the New Testament; it is used by the inspired writers with an evident feeling of exultation.  The very angel of the Lord speaks it with a hushed reverence when he announces the birth of the Lord: --

"Unto you is born this day in the city of David a Savior, which is Christ the Lord."  Luke 2, 11.

It is found in the joyful testimony of the Samaritans of Sychar: --

"Now we believe, not because of thy saving; for we have heard Him ourselves and know that this is indeed the Christ, the Savior of the world."  John 4, 42.

And think of the numerous other passages in which the name is blazoned as on a banner to be borne before the eyes of the believers, to make them realize ever more fully the unspeakable gift of God!  Read them for yourself:  Acts 5, 31; 13, 23; Phil. 3, 20; 2 Tim. 1, 10; Titus 1, 4; 2, 13; 3, 6; 2 Pet. 1, 11; 2, 20; 3, 2. 18; 1 John 4, 14.  

What the name of Jesus indicates, what the angel's explanation proclaims, that is emphasized in Christ's earthly mission.  No one has said it better, no one could express it more definitely than the Lord Himself when He says: --

"The Son of Man is come to save that which was lost."  Matt. 18, 11.  And again: --

"The Son of Man is come to seek and to save that which was lost."  Luke 19, 10.

This is also the clear statement of that "Gospel in a nutshell," given in Christ's own words: --

"God so loved the world that He gave His only-begotten Son, that whosoever believeth in Him should not perish, but have everlasting life."  John 3, 16.

"These things I say that ye might be saved."  John 5, 34.  

"I am the Door; by Me, if any man enter in, He shall be saved."  John 10, 9.

"This is the will of Him that sent Me, that every one which seeth the Son and believeth on Him may have everlasting life, and I will raise him up at the last day."  John 6, 40.

In the very performance of His miracles our Lord's chief gift was that of the forgiveness of sins with its assurance of salvation.  To the man sick of the palsy He gave, first of all, that wonderful certainty: --

"Son, be of good cheer; thy sins be forgiven thee."  Matt. 9, 2; Luke 5, 20.

And when the great sinner knelt at His feet in the house of the Pharisee, the most outstanding gift of Christ is that which He Himself indicates: --

"Wherefore I say unto thee, Her sins, which are many, are forgiven."  Luke 7, 47.

That this winning of souls for the kingdom of God was the object of Christ in all His preaching, in all His work, is obvious from the general tone and tendency of all His acts and all of His precepts.  He tells the former demoniac to preach the kingdom of God.  He summarizes His own invitation in the words:  "Go out quickly into the streets and lanes, highways and hedges, and compel them to come in."  As Dr. Pierson says:  "The command is one which is incarnated in His whole life and is suggested or implied in the very idea of discipleship:  'Follow Me, and I will make you fishers of men.'"

Do we need further evidence to convince us that the obligation of love was the guiding principle of the Savior's life and that the importance of soul-winning in His work is the outstanding feature of the entire Gospel?  If nothing else will impress us, we cannot deny the witness of His death upon the cross.  He Himself says of it: --

"And I, if I be lifted up from the earth, will draw all men unto Me."  John 12, 32.

Read the account of the gospels, the description of the Savior's crucifixion and of His death on Calvary.  Cp. Luke 23, 32-43.

The matter is most beautifully put by St. Paul when he writes: --

"The life which I now live in the flesh I live by the faith of the Son of God, who loved me and gave Himself for me."  Gal. 2, 20.

"Who gave Himself for us that He might redeem us from all iniquity and purify unto Himself a peculiar people."  Titus 2, 14.

Truly, it is a remarkable topic, and one which should duly impress us with the unbounded glory of the love of Jesus in His vicarious redemption and with the fulness of the love which could cause the great Son of God to humble Himself for our sakes.

***

But now comes the test for every one of us.  As St. Paul puts it: -- 

"Let this mind be in you which was also in Christ Jesus, who, being in the form of God, thought it not robbery to be equal with God, but made Himself of no reputation and took upon Him the form of a servant and was made in the likeness of men; and, being found in fashion as a man, He humbled Himself and became obedient unto death, even the death of the cross."  Phil. 2, 5-8.

The mind of Christ was that according to which He felt the obligation laid upon Him by His Father's love and His own; it was the mind which caused Him to be the great Servant of mankind in order to show them the way of salvation.  Jesus Himself calls our attention to this phase of His work: --

"Whosoever will be great among you, let him be your minister; and whosoever will be chief among you, let him be your servant; even as the Son of Man came, not to be ministered unto, but to minister and give His life a ransom for many."  Matt. 20, 26-28.

The obligation of love which rested upon Jesus has passed onto us, who bear His name and are filled with His spirit.  The wonderful union which has been established between Christ and us by virtue of the faith that lives in us has given us some of His power.  Since Christ has made his abode in us, together with the Father and the Holy Ghost, we are in a position to bear much fruit of the kind which He inspires and loves.  We are now, as St. Paul writes, His workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should wlak in them.  Eph. 2, 10.

In accordance with these facts there is one great motto which Christians love to keep before their eyes at all times, namely: --

"The love of Christ constraineth us."  2 Cor. 5, 14.  

Obviously this is not the constraint of the Law and of fear; for "perfect love casteth out fear."  It is the urgency and the power of the love which we have received in Christ, as an outflow of the divine power in Christ, and it is the zeal which now impels us forward for love of Christ, in appreciation of the boundless mercy which we have received.

Is it necessary to emphasize this point any further?  Is the obligation of love brought to our attention to-day and with reference to the situation as we have it before our eyes in the world?  Have we a responsibility which we ought to feel with at least a small fraction of the fervor and zeal shown to us by Christ?

Oh, the need of the world for the love which we alone can bring to men by virtue of the Gospel entrusted to us is still immensely, overwhelmingly great.  It is not only that men are without Christ, in a kind of a neutral situation, but it is that millions of them are living in open and shameful opposition to Him, children of wrath and heirs of eternal damnation.

Here are some of the facts as they are accessible to us to-day with regard to the WORLD WITHOUT CHRIST!

According to the latest available statistics the population of India is 320,000,000.  Now, if we figure all the Protestant societies that are now working in that country of teeming millions (and that includes not a few whose Christianity is of the very liberal kind, not much better than the religion of the heathen themselves), we have far fewer than a million baptized Christians (849,500).  Even if we count all those who are members of the Roman Catholic and of the Syrian churches, we have barely five million Christians!  Barely one and one half percent of the total population -- and the gains that are being made are so heart-breakingly small!  Does our obligation extend to India?

The situation in Southeastern Asia, including Assam, Burma, Siam, and the Malay Peninsula, French Indo-China, that is, all countries east of India and south of China, is as follows.  The population, all told, is somewhat over 53,000,000.  In this great mass there are fewer than 100,000 Christians, and some sections may be said to be altogether unoccupied as yet.  Not even one-fifth of one per cent. won for Christ!

Next comes the immense country of China, with its more than 3,200,000 square miles and its population of 440,000,000.  Do you know that here, ALL TOLD, the number fo communicant Christians has not yet reached the 400,000 mark, although 174 societies are now at work?  The fraction is so infinitesimally small that one hesitates to write it.  Entire provinces are still without so much as one messenger of salvation!

Japan's population exceeds 60,000,000, and we have read so much about Christian leaders in the island empire that we have probably oerestimated the number of Christians.  As a matter of fact, the latest statistics give the number of communicant members of all Protestant missions as not quite 200,000.  Again a number which is quite disheartening in its smallness!

As we go over to Korea, which has had intercourse with the Western World for a matter of only a few years, we find a population of 17,000,000 under Japanese rule.  Although there are many factors in this country which have been found favorable to mission-work, yet the number of Protestant Christians is below 100,000, or not yet one half of one per cent.

As we next look at the Near East, comprising Egypt, Asia Minor (with Armenia and Kurdistan), Syria, Palestine, Arabia, Mesopotamis, and Persia, the situation is still more depressing.  The total population of this section of the world is estimated at almost 55,000,000.  We have here the location of the cradle of the human race, the site of the world's greatest ancient empires, the land of the Bible and of the Savior.  We still have remnants of the Armenian Church, nominally Christian, in Armenia, there are many sects of the Greek Orthodox Church and one or two of the Roman Catholic Church in this section, not to speak of the Coptic Church in Egypt; but the number of Christians is at best very small, and the number of Protestants is as yet below 20,000.

Next we consider Africa, the "Dark Continent."  Its native population is estimated, with some degree of probability, as reaching 150,000,000.  In this entire number there are only three million Protestant Christians, ans possibly seven million more, who are nominally members of the Abyssinian, Coptic, and Roman Catholic churches.  Again the discrepancy is so great that it is appalling.

Latin America includes Central and South America, with a total of 85,000,000.  Til now hardly more than a beginning has been made in bringing the Gospel to this mixed population; for, although almost all the countries concerned are nominally Roman Catholic, yet the number of professed Christians amounts to only a very small percentage of the total, since the workers, all told, amount to barely 2,500.  A moment's reflection will show the utter inadequacy of the present missionary occupation.

Therea re a few spot sin Oceania, or in the islands of the Pacific, which offer a distinct relief.  We are here dealing with Malaysia, Melanesia, Micronesia, and Polynesia, whose combined population is more than 60,000,000.  A few islands are entirely Christianized, but over ninety-five per cent. of the territory is still without the Gospel-message, some sections having not even been touched.

And what shall we say of the unoccupied fields in many parts of the world, which stand as a constant challene before the eyes of Christianity?  Is it the "regions beyond" that offer the most serious problems at the present time, because circumstances have here combined to keep out the name and the Word of Christ.  There is the heart of Asia, with Mongolia, Chinese Turkistan, Tibet, Afghanistan, and Baluchistan; there is the interior of Africa, with almost fifty pagan tribes; there is the heart of South America, many parts of which are not even explored.

That is the challenge to Christianity, that is our obligation of love!

Nor have we as yet mentioned the field wich is both a problem and the most emphatic challenge, at our very doors.  Even if we count all those who are only nominally members of Christian churches in our country, we have

\begin{center} BETWEEN 60 AND 65 PER CENT. OF OUR TOTAL POPULATION NOT WITHIN THE CHURCH \end{center}

Think of it:  some 65,000,000 of our fellow-citizens in this country have not yet accepted the Gospel of Jesus Christ unto their salvation, and, stranger still, many of these have not even heard of their Savior.  In the midst of a so-called Christian civilization, people have never been approached with a view of making them acquainted with the great truths which will bring redemption also to them, the justification which is ready for them in the perfect atonement of Jesus Christ.

And the matter is of unusual interest to

\begin{center} US LUTHERANS! \end{center}

Due partly to the need of gathering those who applied to us for spiritual care during the great immigration from Lutheran and semi-Lutheran countries, partly to the unfortunate language question, we have not yet reached out to our fellow-citizens as opportunity offered.  And what is more, a conservative estimate tells us that 

\begin{center} ABOUT TEN MILLION PEOPLE OF LUTHERAN EXTRACTION IN THIS COUNTRY ARE NOT CONNECTED WITH THE LUTHERAN CHURCH! \end{center}

So many reasons have been advanced for this condition.  But, whatever the reason, these souls are a constant challenge to us, they present to us the 

\begin{center} OPPORTUNITY AND THE OBLIGATION OF LOVE! \end{center}

It is because personal work has been so largely neglected in our midst that the deficit in souls is so great against our Church.  There can be no question concerning the fact that, in addition to the public proclamation of the Gospel, words for christ to the individual are most effective in the winning of sould.  A kind, but earnest word to a negligent churchgoer of our own confirmation class, a tactful invitation to a neighbor, a letter confessing Christ in a frank manner -- these are the things that count with the individual and often serve as entering-wedges for the Word of salvation.

"It is the man-to-man work that tells.  And because it is this work that is most effective, this is the work that is best to do.  Even though it is less attractive work, as we look at it, and seems to others less important to be done, we must admit that the results are worth considering.  As John B Gough said of the one loving word of Joel Stratton that won him:  'My friend, it may be a small matter for you to speak the one word for Christ that wins a needy soul, -- a _small matter to you_, but it is _everything to him_.'  It is forgetting this truth that causes personal work to be neglected."  (_Trumbull_.)

It was the greatest missionary of all times that said, as he summarized the devotion of a lifetime in one sentence: --

"I AM A DEBTOR both to the Greeks and to the barbarians; both to the wise and to the unwise."  Rom. 1, 14.

If we realize the obligation of love resting upon us, 

\begin{center} WE ARE DEBTORS! \end{center}


