# Zealously Affected in a Good Thing! 
## Gal. 4, 18 {.unlisted .unnumbered}
### Qualifications of the Workers. {.unlisted .unnumbered}

The Scripture-passage which we have at the head of the present chapter is peculiarly appropriate to our discussion.  The Apostle Paul was not in sympathy with an attitude which is always ready to receive, the plea being that faith must be disassociated from works.  It is true that saving faith in its essence is the receiving of the grace of God in the Gospel.

But saving faith is, nevertheless, a living faith.  It is a light which not only receives fuel, but which also shines.  The apostle fittingly calls it "faith _which worketh by love_," Gal. 5, 6, that is, a faith which is active in love, which shows itself in works of love.

It is here that we apply the admonition of St. Paul.  He was decidedly impatient with the false teachers among the Galatians, who were trying to lead the believers back into the bondage of the Law, to keep its precepts for the purpose of attaining to a righteousness of works and thus setting aside the righteousness of Christ, the righteousness which comes to men by faith in His vicarious atonement.  For that reason the apostle denounced the false teachers in no uncertain terms, telling the Christians that the interlopers were zealously affecting them, but not well; they were trying to stir them up to a frenzy of work-righteousness, but not in a manner which would really redound to the Christians' highest good.

Over against this wrong position the apostle places the correct principle, that of the Christians' growth in sanctification.  He writes: --

\begin{center} "IT IS GOOD TO BE ZEALOUSLY AFFECTED ALWAYS IN A GOOD THING!" \end{center}

Paul wanted the Galatian Christians to have the proper attitude of affection toward their Lord and Savior at all times, whether he were present or not.  This attitude would result in a zeal for Christ and His kingdom, which would show itself at all times.

There is no finer maxim than the above for the soul-winner, in whom the passion for souls is an every-day matter, who is ever on the lookout for opportunities to be more active in the Lord's service, to fit himself better for the privileges of the church-member, FOR THE WINNING OF SOULS!  

It is these qualifications which concern us in this chapter.  Not as though they would have to be our full possession before we may begin on our task, but that they are placed before us as ideals after which we may strive all our life.  

The fundamental principle, as indicated above, is that of a _faith active in love_.  This faith is not a mere reliance on the ability of Christ as an inspiring leader nor a mere appreciation of His greatness as teacher, as so many Modernists sanctimoniously love to picture it, but it is the acceptance of Jesus Christ as one's personal Savior, who by his vicarious redemption has freed us from the guilt and the punishment of sin.  By virtue of this faith, men are justified in the sight of God, they are declared to be righteous, the perfect righteousness of Christ being imputed to them.

"By grace are ye saved, through fiath; and that not of yourselves, it is the gift of God; not of works, lest any man should boast."  Eph. 2, 8. 9.

While this faith excludes all works of man as having any value for the gaining or keeping of salvation, Rom. 3, 28, by the same token this faith is most decidedly active in love.  In fact, it does not and cannot exist without works, no more than a good tree can be without fruit.  Jas. 2, 17; Matt. 5, 16.  Since God has prepared the good works beforehand that we should walk in them, 2 Cor. 9, 8; Eph. 2, 10, it follows that these works will be plentiful in the measure of our own spiritual life.

"Fruitful in every good work."  Col. 1, 10.

What wonderful opportunities are open to those who are earnestly concerned about the obligation of love resting upon them!

Right here we ought to pause a moment to consider the _power of faith_, that is, of that calm trust in God, connected with saving faith, which relies upon His promises in spite of all difficulties.  We are not strong in our own power, but for that reason the power of God and Christ in us are in a position to do all the more through us.  The assurance which the Lord gave to His apostle is ours also: -- 

"My grace is sufficient for thee; for My strength is made perfect in weakness."  2 Cor. 12, 9.

Paul's conclusion is:  "When I am weak, then am I strong."  2 Cor. 12, 10c.

| 	"When I am weak, then am I strong."
| 	Though hostile armies round me throng
| 	And fill my heart with fear;
| 	Although they jeer on ev'ry side,
| 	My humble faith and trust deride,
| 	And their contempt I bear.

| 	"When I am weak, then am I strong";
| 	When I am conscious of the wrong
| 	That still infests my soul;
| 	When I my utter weakness feel,
| 	No man my bleeding wounds can heal,
| 	No man can make me whole.

| 	"When I am weak, then am I strong";
| 	For Him I count my friends among
| 	Who gave His life for me.
| 	By faith His mighty strength He gives,
| 	By faith my burdened spirit lives,
| 	His love has set me free.

| 	"When I am weak, then am I strong,"
| 	And though the path seem often long,
| 	His love points out the goal;
| 	He guides and leads me day by day,
| 	He keeps me in the narrow way,
| 	He welcomes home my soul.

"I CAN DO ALL THINGS THROUGH CHRIST, WHICH STRENGTHENETH ME!"  Phil. 4, 13.

With faith in Christ as the basis everything else may be accomplished.  This faith brings about a _genuine belief in the work_ in which we are engaged, as one of the supreme things worth while.  The attitude of faith is the attitude of devotion, of actually offering up oneself to the Lord.

"I beseech you, therefore, brethren, by the mercies of God, that ye present your bodies a living sacrifice, holy, acceptable unto God, which is your reasonable service."  Rom. 12, 1.

The choice is not that of a mere intrinsic value and interest, though this factor is important enough in itself, but the attitude plainly says:  I am interested in the work of soul-winning because God wants me to be, and because it is so vitally worth while.  It is one of the highest forms of service and of devotion to Him.

Such an attitude begets _confidence_, not only in the worthiness of the enterprise, but in the certainty of success under God's guidance and with His help.  We have God's command and promise on our side, and therefore our determination must and shall be equal to the definiteness of His Word.

"All things are possible to him that believeth."  Mark 9, 23.

To this personal consecration must be added positive virtues as they are painted so beautifully in the Bible.

There is the virtue of _faith_, that is, of unwavering trust in God and His promises, as described above.

There is the virtue of _love_, whose obligation we are here considering, set before us in the incomparable "Psalm of Love" contained in 1 Cor. 13.

There is the virtue of _hope_, the outgrowth of saving faith, 1 Pet. 1, 3, which looks up to the Lord with the calm certainty that the future will bring the joyful consummation of every expectation as promised in the Word of His mercy.  

But there are other qualifications that the soul-winner must strive after and must cultivate with persistent application.

One of the outstanding characteristics of the great Apostle Paul was his _humility_, with an almost pathetic eagerness to efface himself for the sake of others.  Like Moses, Num. 12, 3, he was meek in the extreme.  And therefore he was in a position to admonish others to show and cultivate true humility in dealing with others.

"With all lowliness and meekness, with long-suffering, forbearing one another in love."  Eph. 4, 2. Cp. Col. 3, 12; Phil. 2, 3; 1 Pet. 5, 5.

Not as though Paul had permitted any man to abuse him and his work for the Lord, for in such a case he was very emphatic in setting offenders right. Cp. 2 Cor. 10, 12-17.

His position was this, that he who gloried should glory in the Lord alone, not seeking honor for himself, but in meekness placing himself and all his talents in the service of the Lord and his fellow-man.  

Such humility, then, does not in any way set aside _firmness and courage_, but rather encourages and supports a definite stand on the basis of Christian liberty.  It is true of soul-winners as it is of all Christians: --

"Stand fast, therefore, in the liberty wherewith Christ hath made us free and be not entangled again with the yoke of bondage."  Gal. 5, 1.

A soul-winner cannot afford to be either foolhardy or cowardly.  This is so important that it shall be discussed at greater length in a later chapter.

Humility also does not interfere with the proper _self-respect_.  A person who has no respect for himself and for his own soul will hardly have much for the soul of another.  The fact that we are "bought with a price" must be brought out so strongly in our consciousness that it shows in all our bearing.  The attitude of some enthusiasts of the early Church, who thought that one must despise himself and cringe in the face of the world, is as bad as a conceit which is overbearing in its behavior toward others.  

A soul-winner needs the virtue of _fidelity_ in a high degree.  This requires, first of all, a staunch loyalty to the Lord, whom he has promised faithfulness.  But it requires also an unwavering devotion to the cause in which we are engaged.  The matter of winning others for the Lord is not an easy task.  It is usually not done with shouting and by means of mass conversions.  It means faithful adherence to the plan adopted as our program, that of making our time and every talent count.

Then there is _veracity_, or _truthfulness_.  Under no circumstances can we afford to be two-faced or even to give the impression of being double-tongued.  Our cause is the essence of truth, and we have no apology to make for any part of it.  We have nothing to hide and nothing to be ashamed of.  St. Paul could truthfully say of himself: -- 

"We spake all these things to you in truth."  2 Cor. 7, 14.  

This implies that we ourselves make use of all _sincerity_, that the truth be not only in our tongue, but in our heart.  The insincere person may have a message which itself is the very acme of truth, but his duplicity will most likely become apparent sooner or later, and the result is apt to be disastrous, not only to such a person himself, but, above all, to the cause and to the message of the Gospel.  

"My little children, let us not love in word, neither in tongue, but in deed and in truth."  1 John 3, 18.

With these characteristics as the basic virtues of the soul-winner, he will be ready to enter upon his work of love with all _enthusiasm_, not with hare-brained precipitation, but with a clear-eyed optimism, with a definite reliance upon the fact that it is God's work which we are carrying on.

For that reason, however, _diligence_, is also needed, a cheerful steady application to the duties imposed upon us by the obligation of love.  We simply cannot afford to dawdle, to stand around idle, with the specious plea that no man has hired us.  Matt. 20, 7.  Our Lord has hired us, and we know that we must apply ourselves most assiduously to the task at hand; for "the night cometh when no man can work."  For that reason we must also observe the talent of time and be punctual in all our work.  Our God is a God of order, and our Savior was punctual in both His incarnation, Gal. 4, 4, and in His death on the cross.  It simply means being conscientious in the duties which the Lord has given us to perform, so that both He and our fellow-men can rely upon us at all times.  There are few experiences more discouraging than to be obliged to wait at meeting for laggards who think that they have the privilege of coming late at their convenience.

A very important virtue of the soul-winner is _patience_, the ability to apply oneself to a task with unflagging interest and with unremitting toil, in spite of the obstacles and difficulties which tend to make the work tedious.  It is not merely that the soul-winner combines patience with faith, love, and meekness in himself, but that he applies this virtue to all the conditions of his endeavor, especially in meeting ignorance and hostility.  We are workers together with God, not in the sense that He and we are a team pulling side by side, but in this, that He works through us, that He makes known the message of salvation through our efforts.  God gives His Holy Spirit when and where He will.

"I have planted, Apollos watered; but God gave the increase.  So, then, neither is he that planteth anything, neither he that watereth, but God, that giveth the increase."  1 Cor. 3, 6. 7.

Another very important point in the make-up of a soul-winner is _tact_, that is, the intuitive, quick, and correct appreciation of that which is fit, proper, and right in a given situation.  Tact is ever kindly and sympathetic; it never takes advantage of any form of weakness on the part of those with whom we are dealing; it wipes out differences of rank and station without diminishing the feeling of respect on the part of him who receives assistance from us.  It succeeds, above all, in removing the feeling of distrust which many people have for such as discuss religious matters with them.  It brings the highest topics of spiritual warfare to a self-evident plane without making them trivial.  At the same time, there is no lack of true politeness and even of affability in approaching people.  We must study the manner in which the Lord Himself approached the various people whom He wanted to win for the Gospel.  He deals differently with John than with Peter, with the woman of Samaria than with Matthew, with the great sinner than with Zaccheus, with the thief on the cross than with Saul, the persecutor.  Philip deals differently with the Ethiopian eunuch than with the people of Samaria.  Paul uses a different approach in the case of Lydia and of the jailer, although both were converted in the same city.

The soul-winner requires _self-denial_; here, again, first for himself, namely, in the sense which Jesus speaks of it: -- 

"If any man will come after Me, let him deny himself and take up his cross and follow Me."  Matt. 16, 24

It is necessary that all boasting be excluded, that the idea of "myself and I and my own righteousness" be set aside emphatically and definitely.

"Ye are My friends if ye do whatsoever I command you."  John 15, 14. 

This self-denial, then, is in evidence whenever the true soul-winner approaches any one who may be gained for the truth.  All thought of self is set aside, and the heart concentrates its efforts upon the one great task in hand, that of convincing the hearer of the truth of the Gospel-message.

| 	Lord, help me live from day to day
| 	In such a self-forgetful way
| 	That even when I kneel to pray
| 	My prayer shall be for -- OTHERS.

| 	Help me in all the work I do
| 	To be sincere and ever true
| 	And know that all I'd do for you
| 	Must needs be done with -- OTHERS.

| 	Let "self" be crucified and slain
| 	And buried deep, and all in vain
| 	May efforts be to rise agian
| 	Unless to live for -- OTHERS.

But all these virtues and many others -- faith, love, hope, humility, firmness, courage, fidelity, veracity, sincerity, enthusiasm, diligence, affability, conscientiousness, politeness, dignity, chastity, self-denial, punctuality, cheerfulness, sympathy, tact -- must be based on _knowledge_; they are useless without such thorough understanding as comes from a diligent study of the Bible.  To depend on emotions alone, on fleeting impressions, on a temporary interest, or to be stimulated by outward success alone, would be the wrong motivation and would certainly not result in a true soul-winning effort.  We must all be willing, eager to study the Word of God and to grow in knowledge of our Savior and the way of sanctification.  We must be willing also to attend classes organized for special training in soul-winning.  We can always learn from others, especially from such as have had personal experience in the work of soul-winning.  It will never do for us to insist upon going our own way when the soul's salvation of so many unnumbered people is concerned.  The work is always under the guidance of those whom the Lord has called to be our teachers.  

"Woe to him that is alone when he falleth; for he hath not another to help him up.... And if one prevail against him, two shall withstand him; and a threefold cord is not quickly broken."  Eccl. 4, 10. 12.

"Where two or three are gathered together in My name, there am I in the midst of them."  Matt. 18, 20.

Let us now summarize the chief qualifications of soul-winners as others have discussed them.

Broughton says that the work side of the soul-winning Church must keep the individual burden before the minds of its members; that no one may shirk the responsibility placed upon him by the Word of God; that the so-called humble talent in the congregation ought to be developed, not merely the rich and prominent people; and that opportunities should be created with the talent at hand.

Kemp says of the qualifications of the soul-winner; 1. He must possess a deep love for the souls of men.  2. He must have an overwhelming passion for the soul's salvation.  3. He must have a deep and heartfelt conviction of the soul's worth.  4. The soul-winner requires tact in his work.

| 	Lord, give us love -- 
| 	The love that flows from Thee,
| 	The love that Thou didst show for us on Calvary
| 	When Thou Thy life laidst down to make us whole.
| 	Let this mind be in us to fill our soul,
| 	That we devote our life to serving Thee
| 	And "Laying down our life for others" may our motto be,
| 	That love may rise in us and grow from day to day
| 	And we be ever guided by its gentle sway, --
| 	Give us such love!


