# The Time is Short.  1 Cor. 7, 29
## Salesmanship for the Lord. {-}

The qualifications which we considered in the last chapter make for a strong Christian personality.  The possession of any one of them or of a group of them is a fine asset to the soul-winner.  But he must not be satisfied with having gained some measure of ability along one line.  It is necessary for him to build up for higher efficiency.  Let us group some of the positive qualities which come into consideration in working for the Lord.

Let us list some of the qualifications of the intellect, of the sensibilities, of the will, and of the spirit, or heart, as they must be highly developed and as they must be kept in the highest possible state of efficiency.

1.  The qualities which are important for _ability_:
	- Observation
	- Concentration
	- Memory
	- Imagination
	- Judgment
	- Reason

2.  The qualities which ensure _reliability_: 
	- Honesty
	- Loyalty
	- Sincerity
	- Ambition
	- Enthusiasm
	- Optimism

3.  The qualities which are essential for _leadership_:
	- Decision
	- Punctuality
	- Courage
	- Initiative

4.  The spiritual qualities which are _required in the soul-winner_:  
	- Eagerness for growth in knowledge
	- Faith
	- Love
	- Hope

Observation is needed to see and develop opportunities and to read the character of people.  Concentration enables one to give the peroper attention to a problem.  Memory ought to be developed for the sake of remembering facts needed in soul-winning efforts.  The imagination must be duly cultivated for the sake of planning campaigns and presenting possibilities.  The judgment ought to be so developed that all ordinary arguments may be both employed and answered.  Reason must be made the handmaid of all our work in the Church.

Honesty will often do more to convince people than arguments in themselves.  Loyalty and faithfulness, together with close application, will create an atmosphere of conviction.  Ambition in the interest of the Lord and His work will tend to bring about an attitude of eagerness to build the kingdom of the Lord.  This will be further aided by enthusiasm and a proper optimism based on the Lord's promises.

If one cultivates the quality of quick and correct decision, he will be dependable in positions of leadership.  Punctuality in all undertakings, in keeping all appointments, enables one to grasp a situation according to its general outlines before others have so much as arrived.  Courage enables one to undertake even a difficult task with a determination which is half the battle.  Initiative finds an opening and takes hold of problems without hesitation.

These qualities must and should be used in SALESMANSHIP FOR THE LORD.

This is necessary because THE TIME IS SHORT.  1 Cor. 7, 29.

"The end of all things is at hand; be ye therefore sober and watch unto prayer."  1 Pet. 4, 7.

"Little children, it is the las time."  1 John 2, 18.

"I must work the works of Him that sent Me while it is day; THE NIGHT COMETH WHEN NO MAN CAN WORK."  John 9, 4.

When a sales manager plans and maps out a campaign and finds that the time for carrying out his objectives is short, he will be all the more careful about instructing his salesmen along the lines of best endeavor.  He will try to communicate to every one of them the mental alertness, the eager tension with which he is himself imbued.  Every movement must count; he cannot afford one moment of lost motion.

Even so, in these last days of the world, every Christian, a soul-winner by virtue of his profession, will strain every nerve to gain souls for the salvation prepared for them in Christ Jesus.

Since we are here chiefly concerned with personal work, we note, first of all, that the soul-winner must _study the individual_ with whom he is dealing.  It is a question of observing faces intently, of determining, by the expression of eyes and features, whether a contact has been, or is being, establishes.  A pleasant and cheerful voice is much more likely to attract than one which grates on the prosect's ear.  The message which we have is to be brought with clearness, force, and elegance.  Clearness appeals to the intellect; force appeals to the emotions; elegance appeals to the taste.  The more we know human nature and the better we are able to analyze the emotions, the better we shall be able to influence them in a manner which will pave the way for a willing acceptance of our invitation for Christ.

We are salesmen for Christ; we are engaged in bringing the blessings of salvation to men who are in need of them; we have orders to call the attention of men everywhere to the wonderful call of the Lord:

"Ho, every one that thirsteth, come ye to the waters; and he that hath no money:  come ye, buy and eat; yea, come, buy wine and milk without money and without price!"  Is. 55, 1.

With this wonderful obligation and responsibility resting upon us, we ought to be familiar with the _seven mental processes_ through which the mind of the missionary prospect must be taken before we can expect him to be interested in the great message of salvation.

First:  He must be met; we must somehow get together with him.

Secondly:  His attention must be attracted to the message which we have for him, and that in such a manner that a favorable mental impression is immediately created in the prospect's mind.

Thirdly:  We must arouse the prospect's interest.

Fourthly:  We must convince him that our proposition is to his advantage.  

Fifthly:  We must cause him, if possible, to have a desire for our message and its contents.

Sixthly:  We must, if possible, add to this desire a positive resolve on the part of the prospect to possess the blessing of which we are speaking.

Seventhly:  We must bring about favorable action on the part of the prospect.

Each of these processes is separate and distinct, although it may be very closely linked up with the one nearest to it.  We must remember that no chain is stronger than its weakest link, and if we fail to prepare for any of these steps, the chances are that we shall lose our prospect.  Let us, therefore, study these steps in greater detail and try to grasp their significance for our work of soul-winning.

First:  THE PROSPECT MUST BE MET -- WE MUST SOMEHOW GET TOGETHER WITH HIM.

This step is usually designated THE APPROACH.  It means that we see the person concerned, if at all possible, in person; for that is the best way for a salesman to see a customer.  Even the best publicity work will not be equal to a meeting face to face or, in our case, a heart-to-heart talk.  If it is a former member of the church whom you wish to see, possibly even a member of your confirmation class, make an appointment with him.  if it is any other person whom you desire to win, call in person, if at all possible.  Letters have usually been found to be very poor substitutes for the personal touch, for the direct approach.  

When the meeting with the prospect takes place, the soul-winner must be altogether clear in his mind as to what he wants to present.  If he is weak in opening the conversation, fidgety and nervous in stating what he has to say, the impression will be very bad and may spoil the whole effort.  If he makes a timid start, the result will probably be the same.  The first sentences should carry with them, and, if possible, produce as well, a feeling of pleasure.  Flippancy is out of place, and familiarity breeds contempt.  The worker should be dignified without being sanctimonious.  His statements should show confidence and strength in the best sense of the word.  First impressions count for very much in the business of soul-winning.

Secondly:  THE PROSPECT'S ATTENTION MUST BE ATTRACTED TO THE MESSAGE WHICH WE HAVE FOR HIM.

This step is usually called GETTING THE ATTENTION, or getting over on the prospect's side of the fence.  The very first thought which ought to reach the prospect's mind is this, that we have something of benefit to him, something that will interest him; that we can demonstrate to him that the proposition which we have to submit will enable him to live more happily here, with the assurance of a good conscience and of heavenly peace.  Sometimes it will make a good impression if, on first meeting the prospect, we can say:  "Mr. (or Mrs., or Miss) ---, let me assure you from the beginning that I have nothing to sell, but I know of a way of happiness which is bound to appeal to you.  All men desire happiness, not the kind that lasts for only a day or two and is then forgotten, but the kind which is connected with security and safety of the most lasting kind."  The object in which we are trying to interest the prospect is not yet mentioned, but a positive suggestion has been made which places the possibility of a benefit squarely up to the prospect.  Notice that at this point we do not in any way put our own persons forward, but rather tend to eliminate ourselves as a factor.  Every suggestion must be positive at this point; for a negative statement is apt to put the prospect on his guard, to place him on the defensive.

Thirdly:  WE MUST AROUSE THE PROSPECT'S INTEREST.

This step is usually called, for short, AROUSING INTEREST.  We keep in mind here that there are various kinds of interest.  There is an involuntary interest, such as that which we feel when a bright picture registers, even momentarily, on our mind.  What we want is to focus or to rivet the attention, to make the interest voluntary, to present our proposition to the prospect in a way which will cause him to listen with eager pleasure.

At this point we can well make use of curiosity, the feeling which desires to become acquainted with some new project.  If we can excite the pleasure of anticipation, the chances are that the interest aroused will be of a nature to accept gratefully whatever we have to offer.  The idea is to hold the prospect's attention until it ripens into a fixed interest.

Sometimes a quick shift of the approach will succeed in arousing the interest, as when a person says:  "I'm not interested in your proposition," and we can immediately counter with:  "But you will surely be interested if I can show you that this will be of great benefit to your children."

Fourthly:  WE MUST CONVINCE THE PROSPECT THAT OUR PROPOSITION IS TO HIS ADVANTAGE.

This step is often designated DEMONSTRATING TO THE POINT OF CONVICTION.  It is not enough that we have the attention of the people to whom we are addressing ourselves in our soul-winning effort.  Nor is it enough that they are interested in what we are demonstrating.  Our further progress must be such as to carry conviction to their minds and hearts.  If our statements up to this point are good, fi we have understood the special difficulties of our prospect, if we have brought hom the necessity of having our message explained, then the next little point must be gained.  The prospect must yield to the extent of thinking or saying, "Yes, I believe you are right," or, "Your proposition appeals to me."  

There is no need, at this time, of making comparisons, unless people bring them in by way of argument.  Our line of talk must still be positive.  When challenges come, the better way is that which Philip chose.  When Nathanael said to him, "Can there any good thing come out of Nazareth?" Philip simply repeated his invitation, "Come and see!"  John 1, 46.  The point of conviction for us is not to convince the prospect, at the first meeting, that the message which we have is the full and whole truth, but only that it is good for him to follow our invitation.  Often people will say, "Undoubtedly I ought to go to some church," or, "Yes, I believe that I ought to send my children to school and Sunday-school."  Then it is when we can say, "Come and see for yourself!"

Fifthly:  WE MUST CAUSE THE PROSPECT, IF POSSIBLE, TO HAVE A DESIRE FOR OUR MESSAGE AND ITS CONTENTS.

This step is usually called CREATING DESIRE.  It is linked up very closely with the preceeding step.  The intellect having been brought to an understanding, the will must now be engaged.  It is here that our reserve talk comes in, where we, in fact, call up all our resources to clinch the matter that we have undertaken.  The prospect's curiosity having been maintained to this point, everything that is irrelevant must be most rigidly excluded, lest the entire undertaking be spoiled by a wrong move.

It is at this stage that objections will very likely be encountered.  The prospect, being convinced in mind, is nto quite ready to yield in action.  The objections may be of a personal nature, either in deprecation of the person himself or in attack upon some member of the church.  Or the objections may be of a critical nature, concerning the matter that is broached.  It will take all our skill to avoid disputes at this point and to offer only clear, positive evidence of the truth which we represent.  This matter will be treated more fully in special chapters.  

Above all, we must not make the mistake of assuming an apologetic attitude at this stage, for that is bound to make just the opposite impression from that which we desire to convey.  There is so much at stake that the slightest digression may throw the matter back to the starting-point and spoil the entire effect.

Sixthly:  WE MUST, IF POSSIBLE, ADD TO THIS DESIRE A POSITIVE RESOLVE ON THE PART OF THE PROSPECT TO POSSESS THE BLESSING OF WHICH WE ARE SPEAKING.

This step may be designated briefly as DEVELOPING THE RESOLVE TO ACCEPT THE INVITATION.  The desire to come has been created, the first step of the yielding has been performed.  But still the prospect hesitates.  There is a fear which is holding him back.  He will come with the evasions of procrastination:  "I guess I won't do it just now yet," or, "Oh, I don't know; there's so much to be considered," or, "Maybe some day."

This hesitancy must be overcome by all means; for if it is allowed to prevail, it will be necessary for the soul-winner to go over the whole ground again, and the will of the prospect is ewakened by every new delay.  One may very well meet this hesitancy in about this way:  "I appreciate your desire to give the matter further thought, Mr.---, but you are really better prepared to make a decision to-day than you will be a week or a month from now.  You see, we have gone over every point very carefully.  The various points are clearer in your mind than they will be later.  Your good judgment tells you that to decide right HERE and NOW is the wise thing to do.  It may take a little courage on your part to go ahead.  You know it is the easiest thing in the world to put off making a decision.  But you will surely agree with me, Mr. ---, that one of the strongest characteristics of prominent and successful men is their ability to decide and act after once making up their mind that it is the wise thing to do; and that is surely what you are going to do.  Your intelligence, your judgment, tells you that this is the best thing you ought to do; your feelings and your best interests make you realize it.  It is only necessary for your will to act, and that can be done by your simply acting according to your own best judgment at once."

Seventhly:  WE MUST BRING ABOUT FAVORABLE ACTION ON THE PART OF THE PROSPECT.

This step has fitly been called GETTING ACTION.  It is the consummation , the climax, of the whole procedure.  Without this step the whole effort is practically wasted.  And, as stated above, the danger is that each new failure in the case of any one prospect diminishes the chances of winning him.  It may be necessary to dispense some final information, which will help the will over the last hurdle.  Above all, only affirmative suggestions are in order at this time.  As soon as one says, "I suppose you would want a little more time to think it over," or words to that effect, the prospect will grasp the opportunity with relief, if not with delight.

AVOID ALL NEGATIVE SUGGESTIONS; NEVER MAKE ONE DURING THE LAST STEPS OF MISSION ENDEAVOR!

Now, if we keep in mind exactly how much depends upon our work, upon the most careful application of the best principles and rules of salesmanship, we shall certainly carry out the suggestions which have proved their value through centuries of selling.

THE TIME IS SHORT!  We cannot afford to waste any time in foolish experimenting.

There is one more point that may be added here for the sake of completeness.  One of the features of our present missionary endeavors is the distribution of tracts and Bibles.  This work is properly carried on only in eonnection with the personal solicitation and appeal.  And it requires a number of suggestions which ought to be studied carefully and heeded without fail.  The most important of these rules are the following: --

1.  Read and master the tract before distributing it to any person.  It may just occur to the prospect to ask questions concerning the contents of the tract, and it would hardly make a favorable impression upon him if you should be obliged to hesitate about entering into a conversation about the topic treated in the tract.

2.  Be sure to hand the tract to the right person.  We do not distribute tracts promiscuously and indiscriminately.  There are few things that so disgust a person as being given information on a point on which he is already sold or in which he has not the slightest interest.

3. Stamp every tract with the name and address of your church or of the pastor of the church.  Unless the prospect knows where to turn when he is ready to act, the whole effort is wasted. 

4.  Carry tracts with you whenever you know you will have an opportunity to reach some one.  This may well be on every trip in or out of the city.  Many tract organizations are having excellent results, due to their custom of distributing tracts in street-cars.

5.  Give tracts at the proper time, at the psychological moment, when the people, if possible, are in the right state of mind to receive just that particular information.

6.  Never give without a suggestion to read.  Sometimes it will be advisable to read a portion to the prospect, especially if he is not at all inclined to read anything of this nature.

7.  Distribute Bibles, Testaments, etc., whenever this is possible and will have any show of success.  A hundred may be given away without results, but the next copy may lead a person to Christ.  The cost is small in comparison with the wonderful possibilities for good.

And don't forget:  THE TIME IS SHORT!


