# Because of His Importunity.  Luke 11, 8
## The Need and Power of Prayer. {-}

One of the most significant, illuminating, and stimulating facts about Jesus is that which tells us that the Savior made _prayer a habit_.  This is all the more remarkable if we consider that this habit on the part of the Lord is reported in such a matter-of-fact way, without the slightest indication of a false enthusiasm in the incidents or in their recital, that the impressin of the account is thereby heightened.  We simply find a wonderful intimacy and fellowship existing between Jesus and His heavenly Father, which found its expression in the act of prayer, not merely as a devotional exercise, but as a form of communication by and through which He derived the support and the strength which He needed for His work.

In the very first months of His public ministry in Galilee, shortly after He had made Capernaum His headquarters, Jesus,

"Rising up a great while before day, went out and departed into a solitary place and THERE PRAYED."  Mark 1, 35.

And again we are told concerning the Savior that 

"He withdrew Himself into the wilderness and PRAYED."  Luke 5, 16.

When the Lord withdrew to the Mount of Transfiguration, it is expressly stated that He PRAYED.  Luke 9, 29.

When Jesus had fed the five thousand men out in the wilderness on the northeastern shore of the Sea of Tiberias, His first act, after dismissing the multitude, is recorded by three of the four evangelists telling the story:  --

"He went up into the mountain apart to PRAY."  Matt. 14, 23; Mark 6, 46; Luke 6, 12.

Of particular interest in this connection are the accounts of the last evening of the Lord's life.  Not only do we find Him speaking about prayer and instructing His disciples concerning its form and proper use, but we have at this time the incomparable high-priestly prayer with its wealth of comfort for all Christians.  John 17.

And who would not think at this point of the narrative of the Lord's suffering in Gethsemane?  We are told that

"He went a little farther and fell on His face and PRAYED."  Matt. 26, 39.

A few verses farther on: -- 

"He went away again the second time and PRAYED."  V. 42.

"And He left them and went away again and PRAYED the third time."  V. 44.

Cp. Mark 14, 35. 39; Luke 22, 41.

Let us consider for a moment what this means as told of our Lord.  As Broughton has it:  "It has always been very striking to me when studying the life of Jesus that, however busy He was, He was NEVER TOO BUSY TO PRAY.  However closely He was beset by problems and difficulties, however great might be the press about Him, He never let the opportunity split by to teach by example and precept the importance of prayer.  I think He often left the great crowd and prayed by Himself because He wanted to teach that prayer was so very important."

Now, Jesus was fully aware of the restriction which concerns prayer in its relation to earthly, temporal things.  When His soul desired reliev from the excruciating torture of a sorrow which brought Him face to face with external death, He yet bowed under the will of His heavenly Father in saying: --

"Nevertheless, not as I will, but as THou wilt."  Matt. 26, 39.  Cp. v. 42.

But in the same measure as Jesus yielded to the will of His heavenly Father int he matter of temporal relief from the cup whose drinking could not be spared Him who had come to be the Savior of mankind.  He demanded the fulfilment of His requests at the hand of His God and Father.

What matchless strength is there in His words:

"Father, _I will_ that they also whom Thou hast given Me be with Me where I am, that they may behold My glory which Thou hast given Me; for Thou lovedst Me before the foundation of the world."  John 17, 24.

What boldness of speech have we here!  WHAT IMPORTUNITY!

And it is precisely this IMPORTUNITY which the Lord requires of us in His work that He expects us to employ in desiring favors and assistance of Him.

"I say unto you, Though he will not rise and give him because he is his friend, yet BECAUSE OF HIS IMPORTUNITY he will rise and give him as many as he needeth."  Luke 11, 8.

This parable illustrates the meaning of the Lord in a most effective manner, especially since it is connected with one of the occasions when the Lord taught His disciples to pray.  There should be an insistence connected with our prayer which knows no failure, which simply clings to the Lord with the importunate declaration: --

"I will not let Thee go except Thou bless me."  Gen. 32, 26.

The same fact is brought out by the Lord in His parable of the widow who was opporessed by her adversary.  If even the unjust judge was constrained to say, "I will avenge her lest by her continual coming she weary me," Luke 18, 5, how much more will our loving Father in heaven be ready to lend us the full measure of His divine assistance in carrying out the work which He Himself has given us to perform!

This spirit of trust in the efficacy of prayer must be ours if we desire to do effective work in carrying out the DIVINE COMMISSION.  It is in agreement with the Lord's own admonitions regarding prayer.  The Savior Himself bids us: -- 

"Ask and it shall be given you; seek and ye shall find; knock, and it shall be opened unto you.  For every one that asketh, receiveth; and he that asketh, findeth; and to him that knocketh it shall be opened."  Luke 11, 9. 10.

His promise is wide and sweeping as long as our requests are voiced in agrement with His holy will.  He says: -- 

"Again I say unto you, That if two of you shall agree on earth as touching anything that they shall ask, it shall be done for them of My Father which is in heaven."  Matt. 18, 19.

Gathered together in the name of the Lord, upheld and stimulated by His divine promises, there is nothing that can daunt us.

AND THIS IS PARTICULARLY TRUE OF SOUL-WINNING.

If the two component parts of soul-winning, according to Hogben, are:  _Going to God for sinners_, and:  _Going to sinners for God_, and both of them have the definite promise of God, being in full aggreement with His will, then surely there can be no flinching on our part as we go forward to perform the task assigned to us.

Again the Savior tells us: -- 

"If ye abide in Me and My words abide in you, _ye shall ask what ye will_, and it shall be done unto you."  John 15, 7.  

Just as all-embracing, within the limits set above, is the other admonition of the Savior: -- 

"Hitherto have ye asked nothing in My name.  Ask, and ye shall receive, that your joy may be full."  John 16, 24.  

Particularly impressive is also the statement made by the Lord in connection with the lesson connected with the drying up of the fig-tree: -- 

"If ye have faith and doubt not, ye shall not only do this which is done to the fig-tree, but also, if ye shall say unto this mounta, Be thou removed and be thou cast into the sea, it shall be done.  And all things, whatsoever ye shall ask in prayer, believing, ye shall receive."  Matt. 21, 21. 22.

Still more emphatic is the declaration made by the Apostle James: -- 

"Ye have not because ye ask not.  Ye ask, and receive not because ye ask amiss."  Jas. 4, 2. 3. 

That, indeed is true:  If our prayer is made in matters which do not have the approval of the Lord, with which His promise is not connected, then we can expect no results.  But what is more definitely in agreement with the will of God and of the Savior than the labor of SOUL-WINNING?

In this connection we must also remember the example of the Lord's saints as told in the Bible.

What wonderful prayers are those of David, the sweet singer of Israel, both these contained in the Psalter and those found in the historical books of the Old Testament!  What a beautiful example is that of Daniel, with his faithfulness in making known his needs to the one true God!  Dan. 6, 10-13.  How much may be learned from other believers of the Old Testament, such as Hannah, the mother of Samuel, Elisa, Hezekiah, Jonah, Nehemiah, and others!

Nor is the New Testament less emphatic in setting forth the need and the advantages of earnest prayer in matters which concern the work of the Church.  The apostles time and again set forth the direct assistance in their work.  When Peter and John had been imprisoned for the sake of the message which they proclaimed, the entire congregation prayed to the Lord with one accord, in a wonderful declaration of faith and trust.  Acts 4, 24-30.  When Peter had been imprisoned by Herod Agrippa I, the congregation of Jerusalem gathered for a meeting of prayer at the house of John Mark's mother.  Acts 12, 12.

Shall we believe that the effectual fervent prayer of the righteous does not avail as much to-day as it did in those days?

Soul-winning is clearly under God's command, agreeing with His direction.  How, then, could He withdraw His promise at a time when His assistance is needed as badly as ever in the history of the world?!

Of course, the work is difficult, and the responsibility is great.  But it is just at this point that we have the assurance of His abiding presence of the gift of the Holy Ghost.  

"If ye, then, being evil, know how to give good gifts unto your children, how much more shall your heavenly Father give the Holy Spirit to them THAT ASK HIM!"  Luke 11, 13.

"PRAYING ALWAYS with all prayer and supplication in the Spirit and watching thereunto with all perseverance and supplication for all saints."  Eph. 6, 18.

Now, the question has been asked by many workers in the Church, just as it is being asked to-day, partly in a spirit of anxiety, partly in a spirit of doubt: -- 

WHY IS THE PRAYER OF SOUL-WINNERS NOT MORE EFFECTIVE!

Various answers may be given according to the bible, and it behooves us to look well to our own hearts and the motives which appear in our work.

Perhaps, when we pray, we have not yet wholly given ourselves to the guidance of the Lord.  Perhaps there is still _some selfishness_, some desire for honor, _some self-righteousness_, in our attitude.  As long as there is some iniquity of this kind in our hearts, the Lord will not hear.  Ps. 66, 18; Job 27, 9.  Such a condition on our part stands in the way of our prayer; it cannot reach the ears of the Lord because of the obstacle which we place in its way.  We are personally responsible for the lack of effectiveness in our petitions in such a case.

There is, in the second place, the ineffectual prayer due to LACK OF FAITH.  Faith, in this connection, means trust in the promise of the Lord, and it is very definitely connected with saving faith, the trust in the forgiveness of sins and in the love of God for Christ's sake.  Faith means that we are ready to undertake a thing for the Lord even if we cannot see and cannot figure out the end and outcome of the undertaking before we take the first step.  God is looking for people, for workers together with Him, who are ready to take Him at His word and promise, so that He may reward their trust accordingly.

It may be, in the third place, that there is a _lack_, on our part, _of free surrender_ to the will of God.  God wants us to plan, of course.  But the manner of carrying out the plan must be in agreement with His Word and promise, not with any false ambition on our part.  Our projects are often tinged with human weakness and with false estimates of men.  If we should insist upon doing our work _only_ in the way according to which _we_ have planned it instead of watching for the Lord's guidance and freely following every hint thrown out to us, it would be all wrong, and we should deserve to fail in our undertaking.

If these conditions obtain, our prayers are bound to be ineffective, and it is entirely our own fault.  The way was open, and we did not take it.  Prayer has its promises, which, when observed, achieve its purpose.  

1.  Definiteness of aim.  It was the singleness of purpose of Elias in his prayer which caused ti to be so powerful.  Jas. 5, 17. 18.

2.  Spirit-taught desire.  It is necessary that we believe in the certainty of our aim and be guided by the Spirit according to the best interests of the kingdom of God.  Mark 11, 24; Rom. 8, 26. 27.

3.  Inward purity, or the absence of self-righteous endeavor.  That is what the Lord teaches in Ps. 66, 18; 1 John 3, 19-22.

4.  Unwavering faith.  "He that wavereth is like a wave of the sea driven with the wind and tossed."  Jas. 1, 6. 7.

5.  Appeal in the name and for the sake of Jesus, the one Redeemer of mankind.  This is a condition which is essential, as the Lord clearly says.  John 14, 13. 14; 15, 16; 16, 23-26.

WE NEED PRAYER

a.  When we p;lan our soul-winning campaigns.  It is true that we should and must use our intelligence and good common sense in making such plans and in preparing to carry out the endeavors connected with them.  If we intend to concentrate on those who have drivted away, we shall naturally use a different approach than if we have in mind the needs of the unchurched.  There is also a vast difference between the various ways of dealing with people belonging to the same class of prospects.  Christ deals altogether differently with the woman of samaria than with the Syrophenician woman, with Peter than with Zaccheus.  But for that very reason we need prayer to guide our intelligent endeavors.

"If any of you lack wisdom, let him ask of God, that givether to all men liberally and upbraideth not; and it shall be given him."  Jas. 1, 5.

It is strange, but true, that the ways of God often differ widely from the ways of men.  In this connection we may well be reminded of the words of the Lord: -- 

"My thoughts are not your thoughts, neither are your ways My ways, saith the Lord.  For as the heavens are higher than the earth, so are My ways higher than your ways and My thoughts than your thoughts."  Is. 55, 8. 9.  Cp. vv. 10. 11.

WE NEED PRAYER

b.  When we are considering individuals.  It is possible, indeed, to divide the prospects into classes, and we observe this distinction in a general way in planning our campaigns.  But soul-winning, in its last analysis, is working with the individual, and it is for the individual soul that we must pray to the Lord.

The necessity of this becomes evident in all cases where former church-members have left the fold or are at the point of doing so.  It will be of assistance to us, of course, if we are acquainted, at least in a general way, with the peculiarities of the individual, so taht we may take these into account in our work.  Very often the personal equation is the most important factor in the winning of a soul.  Where the increasing lack of interest is due merely to negligence, we shall handle the situation differently than where someform of hostility to the Church is in any manner apparent.  But the main point is that which is indicated int he Gospel of St. Luke with regard to teh incident of the denial of Peter.

"And the Lord said, Simon, Simon, behold, Satan hath desired to have you that he may sift you as wheat!  But _I have prayed for thee_ that thy faith fail not; and when thou art converted, strengthen thy brethren."  Luke 22, 31. 32.

Prayer of the right kind will put us into the proper mood and attitude of mind in approaching the individual, no matter what the peculiar condition which must be taken into account.

WE NEED PRAYER

c.  When actually going out on our quest for souls.  This is also true, no matter whether we are considering a general campaign or have some particular person in mind.  A mere physical or intellectual courage alone is not sufficient; in fact, this kind of courage alone may work great harm if a person should rely upon it.  But the matter of spiritual courage, of a reliance upon the promises of the Lord, is a different matter entirely.  This presupposes a passion for souls such as only the power of God can give.  One may expect almost anything when engaged in a systematic mission endeavor:  coldness, indifference, hostility, scorn, derision, mockery, in fact, the whole scale of human weaknesses and wickednesses.  In spite of such expectatinos we must go forth with unwavering determination to WIN SOULS FOR THE LORD.

WE NEED PRAYER

d.  When approaching the individual.  Lt us suppose that all the preliminary steps have been taken, that every move has been most carefully mapped out. We have begun our work.  But here comes the facing of one whom we wish to gain for the message of salvation.  It just may be that the actual opening of the conversation will relieve the strain and that an opening will be given which will enable us to bring our invitation and to have it accepted with some degree of willingness.  It may be, on the other hand, that the reception which is accorded us is anything but encouraging, that, in fact, the person addressed will fly into a rage.  It behooves us, under such circumstances, neither to provode the adversary and cause a quarrel nor to beat an undignified retreat, unless the latter course is positively the only thing left to do.  It may often be possible to leave at least some good literature.  Many a person likes to bluster when first approached.  It may be possible to find a point of contact which will establish friendly relations, if not at once, then at a later date.  All the while, however, the soul-winner will be like Moses.

"And the Lord said unto Moses, _Wherefore criest thou unto me_?  Speak unto the children of Israel that they go forward."  Ex. 14, 15.  

WE NEED PRAYER

e.  In asking for the Holy Spirit and in commending the manner to the Lord.  This was the special comfort with which the Lord setn out His disciples:  

"It shall be given you in that same hour what ye shall speak.  For it is not ye that speak, but the Spirit of your Father, which speaketh in you."  Matt. 10, 19. 20.

We are not indued with apostolic authority and gifts, which were then granted by the direct call of the Lord.  but we have the means of grace to strengthen us, and we have, above all, the Word, which gives us full information concerning the way of life and concerning all other information needed for a life of faith and sanctification.  With this knowledge to sustain us, we can cheerfully rely upon the help of the Holy Ghost in directing our thoughts and minds in speaking to prospects, in tryign to make them conscious of the gifts of God's grace in Christ Jesus.  Prayer will prove a source of power under such circumstances, and -- we are trying to 

\begin{center} GAIN SOULS FOR THE LORD \end{center}


