# I Am Persuaded.  Rom. 8, 38
## Having the Courage of One's Convictions. {-}

The discussion of the present chapter is essential for the purpose of this study.  It speaks of a most important part of the personal equipment of the worker for Christ.  Without the qualification which it imples much of the testifying for Chirist is of an indifferent, mechanical kind, without the force that, in itself, carries the certainty of conviction.

Luther was wont to refer to a man who was not at all times ready to stand up for his convictions as a "soft-stepper."  He did not mean to question the sincerity of any one, but he felt that some of the fundamental principles of the truth were occasionally sacrificed on the altar of what men would like to describe as tact, but which often has its roots in a timidity not at all in keeping with the high ideals held out by the Word of God.

"I AM PERSUADED!  Such was the cry of the Apostle Paul.  The words well represent the fundamental thought which actuated the great missionary and witness for Christ in his life-work.  From the hour of his conversion Paul stands out from the pages of Holy Writ as a man who knew no uncertainty, no vacillation.

No sooner had Paul received Baptism than we read of him: -- 

"Straightway he preached Christ in the synagogs that He is the Son of God."  Acts 9, 20.

"Saul increased the more in strength and confounded the Jews which dwelt at Damascus, proving that this is very Christ."  V. 22.

In the very first letter which has been preserved from the hands of the great missionary, he writes from the hands of the great missionary, he writes with the directness which ever characterized him:

"Our Gospel came not unto you in word only, but also in power and in the Holy Ghost and in much assurance."  1 Thess. 1, 5.

A few years later he wrote to the congregation at Corinth, which had been founded about the time when Paul wrote his letters to the Thessalonians: --

"My speech and my preaching was not with enticing words of man's wisdom, but in demonstration of the Spirit and of power, that your faith should not stand in the wisdom of men, but _in the power of God_."  1 Cor. 2, 4. 5.

This from a man who confesses that, for his own person, he was with the Corinthians in weakness and in fear and in much trembling.  Paul may not have been a courageous man by nature, and he seems to have been affected with some malady which hindered him from being at his best at all times.  2 Cor. 12, 7.

And yet this man, filled with the Spirit of God as he was, could speak of the "great boldness of speech" which he employed in writing to the Corinthians, 2 Cor. 7, 4; he could ask the Ephesians: --

"Pray for me that utterance may be given unto me, that I may _open my mouth boldly_ to make known the mystery of the Gospel."  Eph. 6, 19.

It was the same man who could voice his earnest expectation and hope: --

"That in nothing I shall be ashamed, but that _with all boldness_, as always, so now also, Christ shall be magnified in my body, whether it be by life or by death."  Phil. 1, 20.

No wonder that his friend, the beloved physician Luke, could write of him: --

"Preaching the kingdom of God, and teaching those things which concern the Lord Jesus Christ, _with all confidence_, no man forbidding him."  Acts 28, 31.

What was the basis of this remarkable boldness of the great apostle?  Chiefly, as he himself indicates time and again, the knowledge of his salvation grounded in the Word of Truth.  All his letters breathe this certainty: --

"I know whom I have believed and _am persuaded_ that He is able to keep that which I have committed unto Him against that Day."  2 Tim. 1, 12.

This certainty is expressed also in one of the loftiest passages in all the writings of the great apostle: --

"I AM PERSUADED that neither death nor life, nor angels nor principalities nor powers, nor things present nor things to come, nor height nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus, our Lord."  Rom. 8, 38. 39.

What a glorious persuasion!  How these words "I AM PERSUADED!" ought to stand out before us in appeal and admonition to impart to us some of the spirit of the great missionary!

Is it any wonder that Paul was able to face the howling mob in the court of the Temple upon the occasion of his last visit in Jerusalem?  Acts 22.  Does not this explain the calmness with which he answered the charges of the Jews before the tribunal of Felix?  Acts 24, 10.  Can we note as much as a tremor in him when he uttered his memorable cry, "To Caesar I appeal!"  Acts 25, 11; or when he faced the pomp of Agrippa and Bernice in the same court a short time afterward, Acts 26?

And let us consider for a moment just how this conviction affected the great witness for Christ in his testimony.  Not one iota of the truth was he willing to give up, no matter what the object or the provocation.  Not even for one hour would he be subject to those who desired to bring him and his fellow-workers into bondage, and the entire letter to the Galatians is aglow with a holy zeal for the upholding of a conviction which was rooted in the heart of the Gospel.

Far from designating the attitude of Paul as stubbornness, we must, on the contrary, acknowledge it as an expression of a conviction which challenges the admiration, and invites the emulation, of every true worker of Christ.  That blessed assurance "I AM PERSUADED!" made Paul the great missionary of the Apostolic Age and one of the greatest preachers of all times.

The greatest teacher of the Church since the time of the apostles was Martin Luther, the man who rescued the doctrine of justification from the oblivion of centuries, giving it once more that position in the teaching of the Church which has focused the attention of the world on Jesus Christ as the one and only Savior of mankind.

What was it that made Luther the great teacher of the Church?  What was it that gave him such a power over the hearts of men?  What causes us to feel the profound influence of his personality to this day?

The answer is, briefly, this:  Because Luther had the courage of his convictions.  Like Paul he had grown up in the midst of a religion of self-righteousness.  In a greater measure than Paul he had fought the battle of acceptance in the sight of God on the basis of his own merits.  From the powerful presentation of the great apostle he had learned to know the rock foundation of Christian faith:  the righteousness of Christ revealed in the Gospel.

This knowledge, this understanding, gave Luther the remarkable boldness, the awe-inspiring determination, which is the outstanding feature of his character and work.  The great apostle's mighty "I AM PERSUADED!" lived in this lowly Augustinian, making him one of the greatest heroes the world has ever seen.

Can any one imagine Luther making use of subterfuges or proposing compromises?  The world has paid to Luther the tribute of its admiration on account of his fortitude in that supreme test of courage and conviction when he was cited to appear before the temporal and spiritual princes of the world in Worms.  The very schoolchildren are able to repeat the words which he uttered on the 18th day of April, 1521, when he was asked to recant.  Year after year thousands of hearts thrill to the ringing defiance of the great Reformer: --

"My conscience is bound in God's Word.  I can or will recant nothing, since it is neither safe nor advisable to do aught against conscience.  Here I stand; I cannot do otherwise.  God help me!  Amen."

But some one may say, It is easy enough to play the hero when one has the great mass of the people of any country behind him and knows that popular sentiment is on his side.  To this we answer that these factors were not very strong at the beginning of the sixteenth century, when princes, kings, and emperors ruled with absolute power over their subjects.  But even if we should be willing to make this concession, we have other incidents from the life of the great Reformer which show that the courage of his convictions controlled his actions to the exclusion of every selfish consideration.

If ever, during the entire period when the reformatory movement swept through Europe, it would have been a matter of expediency to have the Protestants offer a united front to the forces of the Church which was at just that time shutting itself out from the truth and going down to the level of a stubborn sectarianism, it was when Philip of Hesse arranged the Colloquy of Marburg, the first days of October, 1529.  No one would have been more gratified at a union of all Protestant bodies than Luther himself.  Because he knew that

\begin{center} THERE CAN BE NO REAL UNION WITHOUT A UNITY ON THE WORD OF GOD! \end{center}

In fourteen points an agreement was reached.  But in the fifteenth point the "different spirit" of the Reformed theologians became evident, a spirit which would sacrifice the Word of God for the sake of man's reason.  To have yielded at this point would have meant to set aside the conviction based upon a clear understanding of the Word of God.  Therefore Luther fortified himself by writing the very word of the Bible (IS) concerning which the controversy was being waged on the table before him.  And then he held out for the truth, not with conceited stubbornness, but as a champion of the unadulterated oracles of God.

The mighty "I AM PERSUADED!" would not permit him to act differently.

Shall not we learn from Luther?

| 	We speak of the _faith_ that lived in his heart,
| 	Which caused him from popery's night to depart,
| 	Which showed him how futile the precepts of men,
| 	Which opened the way to God's mercy again;
| 	We praise him for preaching this saving faith,
| 	Confessing his Savior with his last breath. --
| 	But where would the Church of Luther be
|	If Luther had been like you and me?

|	We tell of the _firmness_ that Luther showed,
| 	Though dark was the outlook and stormy the road;
|	On God's own Word his conviction was based,
|	And though he earth's mightiest ruler faced,
|	His heart refused from the truth to be led:
|	"I cannot do otherwise," boldly he said. --
| 	But where would the Church of Luther be
|	If Luther had been like you and me?

|	In awe we whisper of Luther's _work_,
|	For never he knew what it meant to shirk;
|	His life was spent in serving the Lord,
|	And daily he delved in the life-giving Word;
|	No task was too great and no study too hard,
| 	He cheerfully toiled, with no thought of reward. --
| 	But where would the Church of Luther be
|	If Luther had been like you and me?

Yes, indeed, where would it be?  And where is it going to be in the future, unless we take up this business of SOUL-WINNING with the same force of the courage of our convictions that we admire in Luther?

The Lord asks us to have this courage of our convictions and to carry forward His work with all boldness.  He does not want us to be

"Children, tossed to and fro and carried about with every wind of doctrine, by the sleight of men and cunning craftiness wherewith they lie in wait to deceive."  Eph. 4, 14.

The Apostle Paul censures the Corinthians severly on account of their lack of knowledge and conviction in the matter of their faith: --

"And I, brethren, could not speak unto you as unto spiritual, but as unto carnal, even as unto babes in Christ.  I have fed you with milk and not with meat; for hitherto ye were not able to bear it, neither yet now are ye able."  1 Cor. 3, 1. 2. 

And the writer of the Epistle to the Hebrews speaks just as emphatically in reproving his readers for their deficiency in this respect: --

"When for the time ye ought to be teachers, ye have need that one teach you again which be the first principles of the oracles of God; and are become such as have need of milk and not of strong meat.... Strong meat belongeth to them that are of full age, even those who by reason of use have their senses exercised to discern both good and evil."  Heb. 5, 12-14.

There can be no question regarding the Lord's will.  He wants people as soul-winners who have the knowledge of salvation from His Word and are willing to stand up for their convictions.  Like a trumpet-call the admonition of Peter rings out: --

"Be ready always to give an answer to every man that asketh you a reason of the hope that is in you with meekness and fear."  1 Pet. 3, 15.

This does not mean that we are at any time to brazen it out when we are attacked, but that we be informed and that we stand on this information.  Jude also writes: --

"Ye should earnestly contend for the faith which was once delivered unto the saints."  V. 3.

This is no small matter, but it is a sacred charge, a commission which no believer can evade, as he values the Word of his heavenly Father and of his Savior Jesus Christ.

\begin{center} EARNESTLY CONTEND!  BE READY!  STAND UP FOR JESUS! \end{center}

|	Stand up, stand up for Jesus!
|	The trumpet call obey;
|	Forth to the mighty conflict
|	In this His glorious day.
|	Ye that are men now serve Him
|	Against unnumbered foes;
|	Let courage rise with danger
|	And strength to strength oppose.

Give the Lord the best that is in you!  Go forth in the strength of His might!

This does not mean that we are going to face the world in a challenging manner and with a chip on our shoulder.  It means, rather, that we take up our business of soul-winning with a calm assurance growing out of a certain knowledge of salvation as revealed in God's Word, an assurance which in itself is bound to carry conviction.

Lutheran soul-winners must carry with them this conviction, the definite and invincible assurance, that the Word of God is the truth and that the salvation which it teaches is the one and only road to heaven.

Lutheran soul-winners must carry with them the conviction, the calm certainty, that the Lutheran Church, if really worthy of the name, teaches the doctrines of the Bible in their full truth and administers the Sacraments in agreement with Christ's institution.  If this conviction does not live in us, we cannot be true soul-winners.

We do not mean to say at this point that our Lutheran Church in its outward form is without a flaw.  There was once a sect which demanded that there be not the slightest foible or weakness in the outward appearance and life of the Church and of all its members.  But this demand was rightly discountenanced by the teachers of the Church as being out of harmony with the manner in which the Bible speaks of the outward organization of what we call the visible Church.

But while we must and do admit that there are many things in the outward form of the Lutheran Church which are not in full agreement with the highest demands of sanctification as found in the Bible, that the Church as such, as well as its various members, fall short in their realization of the highest ideals as found in the Bible, we do maintain that, by the grace of God, the doctrine of the Evangelical Lutheran Church is in complete harmony with the revealed will of God, with His Word.

From this it follows that no Lutheran soul-winner will ever be found ashamed of his Church; for that would mean being ashamed of Christ, by whose mercy we have the truth in all its purity in our Confessions and in our teaching.  As workers together with God and with His holy apostle we say:  

"I am not ashamed of the Gospel of Christ; for it is the power of God unto salvation to every one that believeth."  Rom. 1, 16.

|	Ashamed of Jesus!  Just as soon
|	Let midnight be ashamed of noon.
|	'Tis midnight with my soul till He,
|	Bright Morning Star, bids darkness flee.

|	Ashamed of Jesus!  that dear Friend
|	On whom my hopes of heaven depend!
|	No; when I blush, be this my shame,
|	That I no more revere His name.

The soul-winner who is thus equipped will, as a matter of conviction, be _opposed to unionism_.  We are fully aware of the fact that the Lord has those that are His own whenever His Word is still taught, even if this be not in full purity.  There are true children of God in sectarian congregations as long as the Bible is still used in their midst.

But from this fact it does not follow that we can fellowship with sectarian churches, or that we can gloze over the differences in doctrine which separate the various Christian church-bodies.  The words of our Savior are too clear and too direct to be set aside.

"Beware of false prophets, which come to you in sheep's clothing, but inwardly they are ravening wolves."  Matt. 7, 15.

"Be ye not unequally yoked together with unbelievers.  For what fellowship hath righteousness with unrighteousness?  And what communion hath light with darkness?... Wherefore come out from among them and be ye separate, saith the Lord, and touch not the unclean thing."  2 Cor. 6, 14. 17.

We may very well, for our own person, have the conviction that a certain member of another church is a true Christian, and his confession may, in every respect, agree thereto.  But as long as such a person is still a member of a false church-body, that is, of one which openly holds a doctrine or doctrines not in agreement with Scripture, then we cannot fellowship with such a person in public worship as long as unity of doctrine has not been openly established.

The word is too plain:  "TOUCH NOT THE UNCLEAN THING!"

Let us also not be deceived by specious arguments for unionism.  It has been said, All the Christian church-bodies want to get to the same heaven; therefore let us forget all differences and live in harmony and peace.  But there is a big difference between desiring to get somewhere and getting there.  One may want to get to Chicago from St. Louis, but if he starts out in a southeasterly instead of a northeasterly direction, all his good intentions will avail him nothing.

"Can two walk together except they be agreed?"  Amos 3, 3.

We must watch particularly with regard to our own church connection.  While one may get to heaven with a minimum of the Christian truth, such as may be offered in many Christian denominations, the fact that the Lutheran Church holds the maximum of truth makes it imperative that we Lutherans be satisfied with nothing but the full and complete truth.

If a person has all his life drunk nothing but water with some solution of poison in it, his body may have become immune to the poison or may be able to throw off its evil effects.  But one who knows pure water cannot deliberately choose such as contains some poison.  If a person has two glasses of water before him, one strictly pure, the other with just enough pioson in it likely to kill him, he would be committing suicide if he drank the latter.

Thus it is with us.  We have the truth, the full truth.  We cannot afford to be satisfied with less than the full truth.  Moreover, the conviction of our glorious possession must live in us and emanate from us, not in a spirit of intolerance and fanaticism, but of a certainty resting in the Word of God.  If we go out as soul-winners with this attitude to guide us, then the conviction living in our hearts will in itself carry conviction to others; for they will not easily withstand the impression of the holy persuasion with which we go about

\begin{center} OUR FATHER'S BUSINESS! \end{center}


