# By All Means Save Some!  1 Cor. 9, 22.
## Meeting the Unchurched. {-}

BETWEEN SIXTY AND SIXTY-FIVE PER CENT. OF OUR TOTAL POPULATION HAS NO CHURCH AFFILIATION!

Read that sentence again, for we shall consider it once more in connection with the object of the present chapter.  It is a fact which, somehow, must sink into our consciousness by degrees.  It means that an average of six or seven out of every ten persons whom we see on the street, whom we meet on our travels, with whom we deal in a business way, ARE NOT EVEN NOMINALLY CHRISTIANS!

This consciousness is bound to work in us the attitude of St. Paul when he wrote, by the inspiration of the Holy Ghost, the significant words: --

"I am made all things to all men that I might BY ALL MEANS SAVE SOME!"  1 Cor. 9, 22.

The connection in which we find these words is characteristic of the apostle.  We find him, in the first place, asserting with all vehemence his freedom.  No apostle has emphasized this factor more strongly, as when he calls out to the Galatians: --

"Stand fast, therefore, in the liberty wherewith Christ hath made us free and be not entangled again with the yoke of bondage!"  Gal. 5, 1.

If any one was foolish enough to believe his good works were sufficient to earn anything for him in the sight of God, Paul was invariably the first one to disillusion him.

And yet, by a strange apparent paradox, Paul writes: --

"Though I be free from all men, yet have I made myself servant unto all THAT I MIGHT GAIN THE MORE!"  1 Cor. 9, 19.

It is the wonderful truth which Luther also emphasized when he said a Christian is "free from all and no man's servant, but that he is, at the same time, subject to all and every man's servant."

In the field of justification there is only one fact that stands out, namely, the unmerited grace of God in Christ Jesus, our Savior.  In the domain of sanctification the highest ideal is that set forth by Christ:  "Whosoever will be great among you, let him be your minister; and whosoever will be chief among you, let him be your servant."  Matt. 20, 26. 27.

This was the guiding principle of Paul's life, as he briefly shows in describing his manner of work.  To the Jews he became a Jew in order to win the Jews.  Without denying or setting aside one word of the eternal Truth, he accommodated his methods to the circumstances in which he found himself, always with the intention of winning souls for Christ.  He did this in the case of Timothy, Acts 16, 3, in that of the Jews at Jerusalem, since some of the weaker Christians in that city were becoming suspicious of his work, Acts 21, 23ff., and in other instances.  Wherever Paul found that he could yield to weakness and to present lack of information without sacrificing the eternal Truth, he was very ready so to do.

To those under the Law, whether they belonged to the Jewish nation or to the Gentiles (mainly circumcised Gentiles), he became as one under the Law in order to gain those under the Law.  He was willing to conform to the customs, modes of life, and methods of instruction in vogue among them as long as these matters were really things indifferent.  At the same time he never denied the truth or acted in a two-faced manner.

To those without the Law, that is, to the heathen in the strict sense of the word, he became as without the Law, although, as he says, for his own person he was bound under the Law of Christ and was ever eager to do His will in order to gain those without the Law.  When in a heathen community, Paul did not practice the Jewish customs in which he had been trained, for this would merely have antagonized the Gentiles; he omitted all reference to regulations of the Old Testament which were strictly Jewish in character.

To the weak the apostle became weak in order to gain the weak.  His loving insight and gentle tact enabled him to understand the scruples and weaknesses of those who had not as yet made much headway in Christian knowledge.  If the fundamental principles of redemption were not subverted, Paul was ready to exercise patience and kindness to the highest degree.  And all this he did because the love of Christ was the motive for all his actions.  He was possessed of a life of the spirit implanted in his Savior and anxious to demonstrate itself in the service of his fellow-men everywhere.

We, as WORKERS TOGETHER WITH GOD, must learn from Paul, the great missionary, not to despise any one nor to permit disgust over foolish weaknesses and over lack of spiritual information and knowledge to enter our hearts.  It is a wonderful summary which we find here: --

"TO ALL MEN I HAVE BECOME ALL THINGS IN ORDER BY ALL MEANS TO SAVE SOME!"

This is the spirit that appears in the history of missions, especially in that of the early Church.  It explains the consecration with which men and women bore witness to the Gospel of Christ.  Their attitude is well exemplified in the case of Peter and John and their challenging statement: --

"Whether it be right in the sight of God to hearken unto you more than unto God, judge ye.  For WE CANNOT BUT SPEAK THE THINGS WHICH WE HAVE SEEN AND HEARD."  Acts 4, 19. 20.

This spirit explains also the humility which we find in the early workers, with St. Paul at their head, who exclaimed in a passionate outburst: -- 

"Unto me, who AM LESS THAN THE LEAST OF ALL SAINTS, is this grace given that I should preach among the Gentiles the unsearchable riches of Christ."  Eph. 3, 8.

Now let us return to the first statement of the present chapter.  Let us try to realize the fact that

\begin{center} BETWEEN SIXTY AND SIXTY-FIVE PER CENT. OF OUR ENTIRE POPULATION \end{center}

is not even nominally Christian.  This means, according to the Religious Census of the United States, that so many people in our country do not profess to be members of any so-called Christian church-body, neither Protestant (in the widest sense of the term) nor Catholic.  It means that they have no connection with any Church of any type, except, perhaps, that their children occasionally attend some Sunday-school.

It seems almost unbelievable that this should be so, that the many thousands and even millions of our fellow-men and fellow-citizens should declare that they are not personally interested in the Christian religion in even its broadest aspect; but the figures are available for the entire United States, also in the annual figures furnished by Dr. Carroll.  It has been stated that between fifteen and twenty million children in our country are without any instruction in the truths of Christianity.

What is most surprising in the situation, perhaps, is this, that figures coming from rural and semirural districts are not materially different in their totals from those of the larger cities.  Many a small city, even many a town, shows the same proportion of unchurched as the large cities.  It seems strange that hundreds and thousands of people can daily hear church-bells, see church-spires, pass by churches which extend their invitations in various ways, and yet never make a move to investigate the claims of the Church as being an institution for soul-winning.

Now, it has been said by some church-members that people in this country who are born, grow up, live, and die almost within the shadow of a church-steeple have only themselves to blame if they are lost.  This is true enough from God's standpoint.  He expects all men, even on the basis of the slight remnant of the natural knowledge of God (Rom. 1, 18ff.) to "seek the Lord, if haply they might feel after Him and find Him."  Acts 17, 27.

But this is God's privilege, God's perogative.  It does not excuse us from doing the work laid upon us by the DIVINE COMMISSION when the Lord tells us:  "GO YE!"

The UNCHURCHED PEOPLE of America, of any country, are a CONSTANT CHALLENGE TO ALL TRUE BELIEVERS!  We simply MUST go out and meet them!

We must meet the OUT-AND-OUT HOSTILE.  We must remember, in all our work for the Lord, that "the carnal mind is enmity against God," Rom. 8, 7, that is, all men by nature are in a state of enmity, or hostility, against the Gospel.  No man can by his own reason and strength be interested in the Gospel as the message of salvation.  But to this natural aversion against the doctrine of full and free redemption is often added a positive hostility, which aims at the direct destruction of the Gospel news and of its witnesses.

We meet people of this type even without special effort on our part, and we shall certainly meet many more if we engage more generally in specific mission endeavors.  Have you ever tried to sound people with whom you are associated in business, with whom you are working together, whom you meet time and again in a social way?  It is so easy, with the modern form of church publicity, to establish a point of contact, either for positive or for negative results.  One has but to exhibit a pulpit program, a Lenten folder, or some other printed material referring to church activity, with the question, "This will probably interest you?" in order to get some sort of reaction.

In the case of men and women who have grown up without church connection the result of even a casual remark may often yield decided results in establishing a point of contact.  The opening may lead to a discussion of church-work and of church activities, which may result in WINNING a soul for Christ.  The thing to do is to overcome the diffidence, the lack of courage, which is our besetting weakness.  

The most difficult people belonging to this group are such as have fallen away from church; for these are often filled with a bitterness and a hatred for everything connected with church and church activities which amounts to an obsession.  The task is made more difficult in this case by the fact that personal matters often enter into the complication of circumstances, and the people concerned are not in a condition to discuss church-matters with any probability of blessing to themselves.

What we try to do, if this is in any way possible, is to place the suggestion of church in the minds of those with whom we come in contact here.  If we can get enemies of the Gospel merely to listen to an invitation to come to church or to accept a written program of church services, something, at least, is gained.  It is necessary to be careful, of course, lest we cast the pearls of the Gospel before spiritual swine.  If a number of people are present and all of them are in a mood for mockery, we should, indeed, confess our faith, but it would be foolish to provoke a string of mockery which will not serve the cause of the Gospel.  In such cases, however, a word of warning, such as we find in the Bible, may well be left in the hearts of the enemies, such as the statement of Stephen:  "Ye do always resist the Holy Ghost," or the reference of St. Paul to the stubbonness of the human heart:  "Neither murmur ye as some of them also murmured," 1 Cor. 10, 10, or that impressive warning: --

"Harden not your hearts, as in the provocation, in the day of temptation in the wilderness."  Heb. 3, 8.

We must meet the INDIFFERENT.  This is a difficult class to deal with.  It is hart to mold a statue out of treacle.  When people simply assume the position that they are not interested and do not care to become interested, it is hart to make an impression.  It is here that salesmanship for the Lord counts for very much.  In fact, if there is such a thing as concentrated ingenuity or its equivalent, it is needed at this point.  Two points may be remembered in this connection.

The first is that our invitation must be _attractive_.  Just as we try to give a certain appeal to our houses of worship and to the outward form of our worship, in line with the highest treasures of our liturgical and hymnological heritage, so we, in the thoroughly dignified manner and yet with the idea of arousing interest, present our printed invitations.  The proclamation of the Word of God is the center, the climax, of our church services.  But if an invitation carefully worded and tactfully presented, will arouse some unchurched person to such a state of interest as to bring him to church and cause him to hear the Gospel, the effort is not only justifiable, but it is to be commended most highly.

The second point is that of _persistence_.  A person with whom we are dealing may promise five, ten, twenty times to come and always forget or let his indifference guide him.  But it just may be, under the Spirit's gracious sway, that he will come the sixth or eleventh or the twenty-first time.  When Monica, the pious mother of Augustine, was ready to despair because she had, for so many years, tried to gain her son for Christ and had failed, she was very properly consoled with the words:  "It is impossible that a son regarding whom so many prayers have arisen be lost!"  Her persistnce won the day.

We must meet the "BLUE-DOMERS."  These are the people who are influenced falsely by the present movement "back to nature."  The movement has much to commend it; for it tends to bring people out into the open, to God's great out-of-doors, into the fresh air, the uncontaminated sunshine, where they may observe some of the miracles of God's fatherly hand at first hand and get some appreciation of the goodness of Him who "maketh His sun to rise on the evil and on the good and sendeth rain on the just and on the unjust."  Matt. 4, 45.

But there is a great danger connected with the movement, and that danger is becoming more apparent with the increasing number of motorists.  Even church-members and former church-members are being infected with the automobile fever over the week end; how much more such as have never been interested in church!  Since many of these have adopted the phrase about "worshipping the Creator under the _blue dome_ of heaven," they have been designated "blue-domers."

Now we are altogether ready to concede that it is possible to worship God out in the open.  Many of the mission-festivals which are celebrated out in the open have brought rich returns in blessings.  But the fact is that the "blue-domers" are not thinking of services with the preaching of the Word out in the open, their interest being entirely in the "open," and not at all in the "worshipping," although they may occasionally exclaim over the beauty of some landscape.

In speaking to people of this type, it is necessary to emphasize the means of grace which the Lord has given to men, and to mention the advantage of using these means under the most orderly circumstances.  This does not imply an immense cathedral with all the appointments which the love and the wealth of the members can afford; for one may serve the Lord just as well in a small chapel, in a store-room, or in a dug-out.  But the Lord's will with regard to assemblies of Christians for the sake of hearing His Word is very plain: -- 

"Where two or three are gathered together in My name, there am I in the midst of them."  Matt. 18, 20.

"Not forsaking the assembling of ourselves together, as the manner of some is."  Heb. 10, 25.

"He that is of God heareth God's words."  John 8, 47.

"Blessed are they that hear the Word of God and keep it."  Luke 11, 28.

We must meet the spiritual FREE-LANCES, that is, the people who flit from one church to another, without ever becoming members anywhere.  In the parable of the fourfold soil the Lord speaks of seed that falls upon stony places, where there was little earth.

"And forthwith they [the seeds] sprang up because they had no deepness of earth; and when the sun was up, they were scorched; and because they had no root, they withered away."  Matt. 13, 5. 6.

The Lord here speaks of those who believe for a short time.  We may well apply His words also to such as never take root in Church.  Many of these unchurched people are like the Athenians of Paul's day, who were ever on the alert to hear some new thing.  Acts 17, 21.  They are guided by the desire to hear some alleged pulpit orator, or to be found in some beautiful modern temple of worship, or to be associated socially with the more prominent people in the community.  They consider the churches like so many spiritual restaurants, but they never commit themselves definitely to any one of these houses.

It is usually not difficult to interest such people in church matters or church activities as such.  The difficulty is to have them come out of one way or the other with a definite platform of belief and faith.  Their behavior is not in agreement with the Word of God, which clearly speaks of congregations or parishes, which expects us to identify ourselves with a church of the pure Word and Sacraments.  His command is clear: --

"Obey them that have the rule over you and submit yourselves; for they watch for your souls as they that must give account."  Heb. 13, 17.

Sometimes it is possible to reach prospects of this kind with an argument concerning the breaking down of character on account of such practices.  It is not the person who changes opinions and views like his clothes who will command respect, but the man with definite ideas.

"It is a good thing that the heart be established with grace."  Heb. 13, 9.

The most difficult group, in a certain way, is that of the HESITANT.  There are some people who always just about make up their minds to be church-members, but draw back just at the last moments, usually with some sort of flimsy excuse.  Sometimes this is due to vacillation, pure and simple, and then it may sometimes be necessary "to make up their minds for them."  In other words, we must watch for the opportune time and then push the idea of joining to its consummation.  It is just at this point that the last step in salesmanship is important.

It may be advisable, for the sake of just such timid souls, to refer prospective members, not to an "adult catechumen class" or even to a "church-membership class," but to a "class for the discussion of Bible truths," or to the "Bible searchers," or even to the "Bible class."  Since it is a fact that some unchurched people shy at the name "catechumen class," why should we not meet them halfway by simply choosing a name similar to some of those just suggested?

Sometimes the hesitation is due to the fact that a person is secretly addicted to some sin which he finds himself unable to combat successfully.  Very often just such a person needs the advice and the assistance of a consecrated Christian, possibly of a pastor, who can impart such strength from Scriptures to the unfortunate prospect as to cause him to divide definitely for church-membership and all its privileges.

Above all, the SOUL-WINNER will, at this point, study ever more willingly and diligently the great examples of our Savior in dealing with men and women with whom He came in contact.  Of the frankly unchurched with whom He dealt we have the woman of Samaria, the Syrophenician woman, and the demoniac of the Gadarene region.  Our main line of attack will always be the invitation, issues in thousands of forms and with patient repetition: --

"COME AND SEE!"

And let us never forget to put the matter into the hands of God, who alone is able, through His Holy Ghost, to change the unwilling enemies to willing disciples.


