# Patient Toward All Men.  1 Thess. 5, 14.
## Meeting Objections of the Wrongly Informed. {-}

As WORKERS TOGETHER WITH GOD much of our work will naturally concern the unchurched; in fact, this is the only part of our work in which we can be aggressive, in which we can and should take the initiative.

Lutheran soul-winners are not proselyters.  In all our work we follow the admonition of the apostle:

"LET NONE of you suffer...as a BUSY-BODY in other men's matters."  1 Pet. 4, 15.

We find that the Apostolic Church was ever most careful in avoiding the offense, according to which men break int othe herd of another and steal his sheep.  The transgression is commonly known as "sheep-stealing" and is rightly detested by all such as uphold the dignity of the Church and the rights of the Lord's servants.  The demand of the Lord is simply this, that we should not take the initiative in getting people to join our church who are members of any Christian denomination, not only of another congregation of our own church, but of any church of which we have evidence that it is still rightly designated as a Christian church.  This means, generally speaking, acceptance of the Bible as the Word of God, believ in the Triune God of Scriptures and in Jesus Christ as the only Redeemer of mankind, and the use of the means of grace in public worship.  In this sense we regard all the Reformed bodies (Presbyterians, Eposcopalians, Baptists, Methodists, Christian Reformed, etc), with the exception of the Campbellites, as well as the Catholics, as Christian bodies.  But we do not so regard the Unitarians, the Universalists, the Mormons, the Christian Scientists, the Spiritualists, and many other bodies of the same kind, for all of these deny the Trinity of the Bible.

With regard to members of non-Christian bodies the same rules are observed as apply to the unchurched.  With regard to such as are members of a body which causes us to regard it as Christian we follow the rule of Holy Writ which states that we are not to interfere, not to take the initiative in getting their members to join our Church.  It is most fortunate, as one Church Father puts it, that "the ears of the hearers in such denominations are often purer than the lips of their teachers"; that is, by the grace of God and the enlightenment of the Holy Spirit, many false statements made by their teachers are stripped of their falseness in being transmitted to the hearers, or many of the latter rely upon the Word which they study at home and promptly forget the incorrect teaching which was brought to them in their own church.

At the same time we welcome such people if they, of their own initiative, come to our services or approach us in their search for the full truth.  Since, by the grace of God, we are in possession of the full truth in Christian doctrine, we are UNDER THE OBLIGATION OF LOVE to impart this bleassing to all who seek it.  That is the object of all our advertising, to call the attention of men to the saving truth which we possess and which should by us be made known to others.  Even if such people are, at first, only visitors at our services, we bid them a cordial welcome, asking them to judge for themselves whether we teach the full truth of the Bible or not.  Of the people of Berea it is stated with approval: --

"These were more noble than those in Thessalonica, in that they received the Word with all readiness of mind and searched the Scriptures daily _whether those things were so_."  Acts 17, 11.

We take the same attitude with regard to those who approach us privately or who broach the subject of religion and of Christian doctrine in a conversation anywhere.  This gives us an opportunity to testify for the truth, and our testimony may prove the entering-wedge for the Gospel-message in all its purity.  

The Apostle Paul indicates to us in what spirit the work with the wrongly informed should be carried on.

"Now we exhort you, brethren, warn them that are unruly, comfort the feeble-minded [faint-hearted], support the weak, BE PATIENT TOWARD ALL MEN!"  1 Thess. 5, 14.

The spirit of Paul was the spirit of Christ.  Jesus also hated sin, but loved the sinner, not with a weak sentimentality, but with an unspeakable yearning for the salvation of his soul.  And therefore we, too, must let the same mind dwell in us.  While we are impatient for the glory of the Lord and jealous for the full truth of the Bible, we are PATIENT WITH THE WEAKNESS AND THE DULNESS of men in spiritual matters.

We have the background of hundreds of years of sound Gospel-preaching; we have the background of a thorough indoctrination, preferably in the Christian day-school; we have the background of church customs which are hallowed by centuries of use and have a significance which has endeared them to us.  

But now people come to us who are wrongly informed concerning many of these facts.  Others begin to argue with us on the basis of a false prejudice.  And very contradictory statements indeed are those that come to our attention.  One says:  "Why, you Lutherans are just like the Catholics; you have altars in your churches, and you use the cross in your services."  Others say:  "You Lutherans are just like the Presbyterians, or like the Methodists -- you are so strict with regard to worldly amusements."  The number of objections which have been voiced might be continued almost indefinitely.

A Lutheran SOUL-WINNER ought to be in a position to meet such objections; for it is not at all difficult so to do, especially if one uses a little common sense.  

If the objection concerns our Christian DAY-SCHOOLS, we can readily oint to the fact that hundreds of the foremost educators of our country have declared that an education without religion, without the Word of God, is deficient in an essential point.  We are merely following the injunction of the Word of God in indoctrinating our children.  We may, in this connection, make good use of various tracts published by Concordia Publishing House and by the American Lutheran Publicity Bureau.

If people find it strange that we have altars in our churches, we ought to point out to them that the altar in our churches is nothing but a table for the celebration of the Eucharist.  The pictures and statues which we have on our altars are not used for idolatrous purposes, and everything that is in itself objectionable in such pictures has been eliminated.  We ought to be acquainted, in this connection, with the labors of Luther to purify the services of the Church.  This information is available in some of our own publications.

If people object to the use of the cross on our churches and as a token of remembrance, reminding us of the bitter suffering and the vicarious death of our Savior, we ask them whether they are ashamed of this token and its significance.  We ascribe no magical power in the sign of the cross, but use it merely as a remembrance of the miracle of our redemption.  Fortunately the senseless opposition to the use of the cross is disappearing, and we find it in use on many Reformed church-buildings.

If people object to the use of gowns by our pastors, we can readily point out to them that our pulpit gowns have been retained with a very good liturgical reason.  The pastor, in his official position, especially as preacher and celebrant of the Holy Communion in the church, is acting not for his own person, but by virtue of his call and as the representative of Christ.  Therefore even his ordinary clothes are covered and his own person is eliminated as much as possible.  No individual performance is the messenger of the Lord indicates by his gown that he declares his message to be:  "Thus saith the Lord."

If people object to our unequivocal stand with regard to worldliness and carnal amusements, we are in a position to tell them that our Church does not think of condemning anything that is permitted in Scriptures.  In the prohibition discussion and many other topics which have agitated the minds of church people in this country and elsewhere we were able to maintain a calm aloofness simply because we adopted the standpoint of the Bible.

There may be many another point which we will be injected into a discussion by the wrongly informed with regard to outward forms and ceremonies or with regard to the so-called position of the Lutheran Church on questions agitating the public mind, but in practically every case the well-informed Lutheran soul-winner will be able to meet the objection or at least parry the attack until he has gained further information for himself.

HENCE THE NEED OF CLASSES FOR THE INFORMATION AND INSTRUCTION OF SOUL-WINNERS.  _Let everything be done under the auspices of the congregation -- if possible, under the personal direction of the pastor, who possesses all or much of the information needed or knows where he may get additional information on short notice!_

But there is another class of people to be considered here, namely, those who are WRONGLY INFORMED with regard to the DOCTRINES OF THE BIBLE.  Some of these are seeking the truth and come to us with open minds.  Others adopt a more or less challenging attitude, which demands _"to be shown."_  WE OUGHT TO BE IN A POSITION TO SHOW THEM.  Every Lutheran soul-winner ought to be sufficiently well informed regarding the fundamental doctrines of the Bible to be able, if need be, to point out the falseness of the sectarian position.

With regard to members of _non-Christian organizations_, who usually adorn themselves with the Christian name, our position is clear.  They are to be regarded as being entirely outside the pale of Christianity, our approach, in thieir case, being almost entirely the same as in the case of pagans.  It may not always be wise to state in so many words that the prospect cannot be considered a Christian, for he may regard himself as such, not having the slightest notion wherein the essence of the Christian faith consists.  But our manner of dealing with such people will be in the nature of patient instruction concerning the fundamentals of saving faith, especially the doctrine of justification.

When members of the _Roman Catholic Church_ come to us, we often find that theya re already convinced of the falseness of many claims made by the Pope.  Our task is not so much an emphasizing of that which is wrong int he Roman Church as in bringing out the beauty of the glory and the comfort of the Bible doctrine as taught in the Lutheran Church.  But it is well to have on hand some of the chief Scripture-passages directed against the outstanding abuses in Romish doctrine and life.  With regard to the doctrine of works and self-righteousness as officially held in the Pope's Church we remember: --

"We conclude that a man is justified by faith, without the deeds of the Law."  Rom. 3, 28.

"By grace are ye saved, through faith; and that not of yourselves, it is the gift of God; not of works, lest any man should boast."  Eph. 2, 8. 9.

With regard to the worship of Many as practiced in the Catholic Church, we keep in mind Mary's own words expressing her need of a Redeemer: --

"My spirit hath rejoiced in God, my Savior."  Luke 1, 47.

And with regard to the other saint-worship of the Catholic Church, we ought to remember the passage from the story of Cornelius and Peter: --

"And as Peter was coming in, Cornelius met him and fell down at his feet and worshiped him.  But Peter took him up, saying, Stand up; I myself am also a man."  Acts 10, 25. 26.

If Catholics accuse us of not acknowledging good works, we may safely refer them to the statements of our Confessions on this point, for they agree exactly with the demand of the Bible: --

"In Jesus Christ neither circumcision availeth anything nor uncircumcision, but FAITH, WHICH WORKETH BY LOVE."  Gal. 5, 6.  Cp. vv. 1-5.

With regard to the REFORMED church-bodies in general, we ought to remember that the "different spirit" of which Luther complained at Marburg, in 1529, consists chiefly in this, that they have permitted reason to be the judge of Scriptures.  It was this point which proved the decisive factor and which has definitely kept the Lutheran and the Reformed churches apart; for the so-called United-Evangelical Church of Germany and other countries is not a homogeneous mass, but a conglomeration.

God does not want us to deny or set aside human reason in dealing with the eternal truths of His Word, but, as St. Paul has it: --

"Bringing into captivity every thought to the obedience of Christ." 2 Cor. 10, 5.

That is to say:  The greater wisdom is God's, as reason itself must acknowledge.  What we are to do is to accept the divine truths without question, knowing that they are essentially above and beyond our reason.

"We preach Christ crucified, unto the Jews a stumbling-block and unto the Greeks foolishness, but unto them which are called, both Jews and Greeks, Christ the Power of God and the Wisdom of God.  Because the foolishness fo God is wiser than men, and the weakness of God is stronger than men."  1 Cor. 1, 23-25.

As far as the CHRISTIANS, or CAMPBELLITES, are concerned, it is rather difficult to fix their status, since they disclaim any confessions.  Naturally we turn to their publications, only to find that there are indications pointing to a denial of the Trinity of the Bible.  But the situation, on the whole, may be said to be not quite that bad.  That is, individual congregations and individual members of Campbellite congregations may be sincere enough in their confession of Christianity.  If they are, we must deal with them partly on the basis of what has been said regarding Reformed bodies in general, partly on the basis of what must be kept in mind concerning the Baptists.  

The necessity of meeting the BAPTISTS with clear arguments from Scripture is apparent almost every day.  Their viewpoint, in general, is that of the Reformed bodies, but their vary particular characteristic is that connected with Baptism, especially their rejection of child baptism and their insistence upon immersion as the only correct form of baptism.

In rejecting the baptism of children, the Baptist bodies are pretty well a unit in declaring that the command to baptize does not concern children and that children can have no faith.  They like to quote with approval the text Matt. 28, 20:  "Go ye therefore and teach all nations, baptizing them in the name of the Father and of the Son and of the Holy Ghost."  The argument is that, according to the text, the teaching must come first and then the baptizing.  But, aside from the fact that even the English translation, with its participle, indicates that the baptizing should at least go hand in hand with the teaching, we know that the Greek text reads: --

"Make disciples of all nations BY BAPTIZING THEM."

As for a command of the Lord to baptize children, it is included in the very words of the divine commission, which expressly speaks of all "nations>"  Neither men nor women nor children are separately or distinctly mentioned, for all three are included in the word "nations."

We must also remember what Peter told his audience in his great sermon on Pentecost Day: --

"Repent and be baptized, every one of you.... For the promise is unto you _and to your children_."  Acts 2, 39.

If the argument is advanced that children, especially infants, cannot have the saving faith in their hearts, we point to such passages as the following: --

"Whoso shall offend one of these little ones which believe in Me."  Matt. 18, 6.

"And that from a child [from infancy] thou hast known the Holy Scriptures, which are able to make thee wise unto salvation."  2 Tim. 3, 15.

The argument as to the _form_ of baptism is often perplexing, since the contention is made that the word _baptizein_, in the classical language, means only "to immerse," and since Luther expressed himself as preferring this form of applying the water. -- We keep in mind here that the usage of the word in the Bible determines its meaning, and we note that the word _baptizein_ is used as a synonym of _niptein_, which clearly means "to wash."

"The Pharisees and all the Jews, except they wash (_niptein_) their hands oft, eat not.... And when they come from the market, except they wash (_baptizein_), they eat not.  And many other things there be which they have received to hold, as the washing (_baptismous_) of cups, and pots, and brazen vessels, and of tables."  Mark 7, 3. 4.

"And when the Pharisee saw it, he marveled that He and not first washed (_baptizein_) before dinner."  Luke 11, 38.

The reference is to the washing of the hands as it was practiced by the Jews before sitting down to a meal, and yet the word _baptizein_ is used.

The point that we insist upon is this, that our liberty in the choice of methods of applying the water be not interfered with.  The essential thing is that water be applied; beyond this nothing is commanded by God.

With regard to the PRESBYTERIANS and all Reformed bodies of a strongly Calvinistic trend, it is to be noted that they want to confine the counsel of God regarding the salvation of men to the elect only, not for all men.  Over against this terrible doctrine we hold the clear words of Scripture: --

"Got so loved the _world_ that He gave His only-begotten Son."  John 3, 16.

"Christ died _for all_."  2 Cor. 5, 15.

"God will have _all men_ to be saved and to come unto the knowledge of the truth."  1 Tim. 2, 4.

The Bible knows nothing of an electino to eternal damnation, and the reason why the great majority of men are not actually saved is not to be sought in God, but in their own perversity, according to which they reject the counsel of God's love.

As for the METHODISTS, many of them are perfectionists, that is, they hold that men who have come to fiath are altogether without sin.  Now, it is true that the believers, by virtue of their baptism, and by virtue of their faith which receives the full atonement of Christ, are pure and clean in the sight of God.  John 15, 3.  According to the new man, the new nature which is ours by virtue of our conversion, we are holy in the sight of God.  But according to the evil nature which we still bear around with us, which we combat all our lives, we are sinful and require daily contrition and repentance.

"If we say we have no sin, we deceive ourselves and the truth is not in us.  If we confess our sins, He is faithful and just to forgive us our sins and to cleanse us from all unrighteousness."  1 John 1, 8. 9.  Cp. Rom. 7, 14-24.

So far as the EPISCOPALIANS are concerned, very much depends upon their particular interests, whether they are High Church or Low Church people.  Their confessions mean little, and each case must be judged on its own merits or demerits.

Many of the Protestant churches of our day are under the influence of Modernism and deny the fundamental facts of Holy Writ.  Whenever this is the case, we govern ourselves accordingly, treating the people concerned as unchurched.  At the same time, we do not wish to be identified with the Fundamentalists, much as we appreciate their stand on many of the doctrines defended by them.  The thing for these Fundamentalists to do is to follow the injunction of the Bible:  "Come out from among them and be ye separate."  2 Cor. 6, 17.  If the sifting has been done, we are in a position to meet them.

Meanwhile let us continue to MEET THE OBJECTIONS of the wrongly informed with PATIENCE TOWARD ALL MEN!


