# Let Us Not Be Weary.  Gal. 6, 9
## Follow-Up Work. {-}

There is a reason for selecting the heading of this chapterin just that form: --

LET US NOT BE WEARY!

There is a reason for selecting the heading of this chapter in just that form: --

LET US NOT BE WEARY!

The work of th epersonal mission-canvass is not easy.  It often requires all the believer's physical and spiritual stamina.  The great majority of people in the world are not interested in the message of salvation.  The number of cheerful greetings on the part of those visited will be comparatively few.  It does happen, of course, that people are frankly delighted to have us call and show a personal interest in them.  That is when the canvasser feels the rich blessing which attends the soul-winner.  

On the whole, it may be said that the systematic canvass has certain elements that make it attractive. There is the combination of talents and energy; there is the stimulation of the contact with kindred minds bent upon the accomplishment of a great object; there is the exhiliration of the work itself; for there is always the possibility of finding souls that hunger and thirst after righteousness.

It is different, on the whole, with FOLLOW-UP WORK.  There the preliminary report has been made, the possiblity of new and encouraging discoveries is fairly remote.  Follow-up work means to use endless kindness and tact and patience in keeping alive the spark of interest and in kindling it into a warm and bright flame.  It means, in some cases, losing people who seemed to be fairly good prospects because they, after all, prefer the ways of the world to the ways of the Church.  It means finding oneself in the spiritual condition of Elijah when he cried out in the bitterness of his heart: --

"It is enough; now, O Lord, take away my life, for I am not better than my fathers... The children of Israel have forsaken Thy covenant, thrown down Thine altars, and slain Thy prophets with the sword; and I, even I only, am left."  1 Kings 19, 4. 10.  

For this reason the words of the holy apostle are so wonderful for the soul-winner at this stage: --

"LET US NOT BE WEARY IN WELL-DOING; for in due season we shall reap, IF WE FAINT NOT.  _As we have therefore opportunity_, let us do good unto all men, especially unto them who are of the household of faith."  Gal. 6, 9. 10.

In this we ought to be strengthened particularly by a consideration of the mercy of God in His follow-up work for men.  There are the countless evidences of His love and grace in dealing with entire nations.  With what unspeakably wonderful kindness and patience did He deal with His chosen people in the Old Testament!  As often as they provoked Him to anger with their murmuring and with their idolatry, He nevertheless turned to them in mercy whenever they repented and cried to Him for help.  

"The Lord testified against Israel and against Judah by all the prophets and by all the seers, saying, Turn ye from your evil ways and keep My commandments and My statutes, according to all the Law which I commanded your fathers, and which I sent to you by My servants, the prophets."  2 Kings 17, 13.

Even when the Lord was finally provoked to such depths of anger as to have Israel removed from the Land of Promise, He caused the more serious people in its midst to cast their lot with Judah; and even when Judah was led astray into captivity, He promised deliverance and return to those who would seek His face.  And let us not forget that from the remnant of the covenant people who returned to the land of their fathers the Lord chose a maiden to be mother of the Redeemer, and Christ's first personal followers, the nucleus of the New Testament Church, were people who were descendants of Abraham according to the flesh.

Of such a nature is the Lord's FOLLOW-UP WORK!

And he shows the same patient love in dealing with individuals.  Where would David have been if the Lord had not sought him again and again when he sinned?  What would have become of Peter if there had been no room for repentance after his denial of his Savior?

We have but to examine our own lives to realize, in a measure, the patience of God in dealing with us poor sinners.  As often as we have provoked Him, not only with small transgressions, but with great and deliberate sins, and that time and again, He has been ready to forgive and to forget and to pour out on us once more the fulness of His mercy in Christ Jesus.

That is true FOLLOW-UP WORK, such as we are to learn from the Lord!

In order to do real follow-up work, then, it is necessary for the worker to intensify whatever previous impressions of soul-winning he has gained.  He must dwell, time and again, on the _example of Scripture_, which must cause us to bring the invitation of Philip with patient repetition: --

"COME AND SEE" John 1, 46.

No matter what objections are brought by those whom we are trying to win for Christ, and no matter how often we have confessed our belief in the Bible and all its doctrines, the final call which we must issue to all men everywhere is to COME AND SEE.  Let them but examine our Confessions, let them but hear our sermons, let them but search the Scriptures, -- that is what we ask, knowing that the Holy Spirit, working through the Word, will kindle faith where and when He will.

We have the opportunity, in follow-up work, to _concentrate in prayer_.  We are no longer dealing with the problem as a whole, we are not regarding the indefinite in persons, but we have certain people to deal with.  Of these people we possess some information, not much, perhaps, but enough to say to the Lord:  "Be hold, he whom Thou lovest is sock."  We can present the particular difficulties of each case to the Lord, reminding Him, at the same time, that He has taught to wrestle with Him for the souls of men and that He has given us the promise: --

"My Word shall not return unto Me void!" Is. 55, 11.

Follow-up work means that we are going to be much more interested in _personal work in the congregation_.  There are so many ways in which we can be of use to the Lord in the work which is already established, in teaching Sunday-school, in serving on committees, in doing clerical work, in being present at meetings where the weal and woe of the church is discussed.  The greater our interest in this phase of church-work, the more we shall be prepared to serve the Lord in follow-up work dealing with prospective members.

Follow-up work means a _life in the Word of God_.  The Gospel, the Word of God, is the only source of spiritual life and energy which we have, the Holy Eucharist being the visible form of this Word.  The more deeply we penetrate into the riches of the knowledge of God, especially as it is revealed to us in Christ, the more we shall be prepared to be soul-winners in follow up work.

Now as for the APPROACH ITSELF.  This depends largely upon the contact in the canvass and in the campaign by mail.  Where the prospect is practically gained, it remains to clinch his resolve.  If he is favorably inclined toward accepting the invitation which has been extended to him, a tactful reminder will probably suffice.  It is at this point that the words which St. Paul writes to the Corinthians ought to be kept in mind: --

"I seek not yours, but you." 2 Cor. 12, 14.

Many people are extremely sensitive with regard to joining a church, for they have the strange notion that the church seeks them only on account of their contributions.  Our task is to convey to all prospects the assurance that we are offering them in the Gospel far greater spiritual gifts than they can ever hope to pay for with all the wealth of the world's gold-fields.  

In the case of those who are less favorably inclined or apparently hopeless we are inclined to give up too soon, particularly after the experience of a very stinging rebuff.  Let us not forget that there is an importunity of faith which does not know the word Failure until the Lord Himself has indicated that further work is useless.

NEVER GIVE UP UNTIL THE WORK IS DEFINITELY IN VAIN!

The number of calls which we make may be reduced, but the name of any prospect should not be taken from our mailing-lists until a conclusive demonstration of such a hardening of heart has been brought as to convince us that we should, by further efforts, be casting our pearls before swine.

Let us now summarize what may be said under the heading of follow-up work.

It stands to reason that this task should be undertaken _as soon as possible after the canvass itself_.  The enthusiasm of the campaign must not be spent, otherwise the reaction may find us in an apathetic mood.  If the various teams have been working together with the proper zeal, they will probably be ready to go out for personal follow-up work in the district covered by them.  They will look up all the people listed under Group A and invite them personally to come to services.  If a special church service can be arranged and a definite, printed invitation be extended, much will be gained.  But the emphasis on this feature must not be too strong, otherwise the special stimulus will always be expected, and the reaction is apt to be that following sectarian revivals.  Our aim is indoctrination, and to that end we must have regular church attendance on the part of the prospects.

Above all, a positive and definite approach will rarely fail of success.  If parents have promised to send their children to Sunday-school, arrangements should be made according to which some one will call for the children at least on the first Sunday, if not for an indefinite period, until they have become accustomed to the idea of coming themselves.  If older people seem diffident, arrange to have some church-member living in the neighborhood call for them and accompany them to church.  If the church-member ordinarily comes to c hurch in his auto, the ride may be a secondary inducement for them to go along, warding off excuses pertaining to the weather.  Care should be exercised that all people not only come to church, but also meet the pastor, if this may at all be arranged.

Be at church yourself, with a friendly greeting for such prospects as you have personally met.  See that other members of the church are also given an opportunity to say a word of welcome.  Be sure to avoid even the appearance of snobbery, the respect of persons, which is so severely condemned in the Bible.  _Read Jas. 2, 1-9_.

The organization of the committees and of the teams ought to be kept intact for at least a year at a time.  This is necessary because the pastor may not be able to visit all prospects in a short time, and it is he who should by all means get in touch with such as have become interested, or may become interested, in the work of the Church.  It will be advisable also that the workers, in assisting the various committes, keep in touch with all those listed, not only in Group A, but also in Group B and C, by personal visits if possible, and at least by the sending of letters of invitation and other literature, such as announcements of special services, parish-papers, pulpit programs, and other forms of publicity.  If Lenten services are held in a city or community, the announcements of such services should certainly reach every person on the congregation's mailing-list.

As stated above, if there are children concerned all efforts must be bent toward gaining them at least for the Sunday-school, but, if possible, also for the day-school.  If there are children past the junior age and adults who are not yet confirmed, they should be tactfully induced to attend the special classes arranged for such as desire to become acquainted with the Bible truth as taught in our Church.  in every case talk over the matter with _your pastor first_.  This suggestion applies especially in the case of older people whom one would like to interest in church-membership and in the joining of church societies.  While all prospects may be invited most urgently to attend meetings, particularly the social meetings of the various organizations in the church, the eligibility to membership must be discussed with the pastor and the church authorities first.  Of course, if there is no valid reason which would prevent their joining, and especially if they have been admitted to the Lord's Supper by the pastor, then, all other things being equal, they may be admitted to the various societies.  If the prospects have any ability or accomplishment along any lines whatsoever, -- the faculty to teach, to sing, or some other talent, -- they may become useful members of the various organizations concerned.

But let ALL THINGS BE DONE DECENTLY AND IN ORDER and with the object of winning souls for the Lord.  For that is the spirit in which our work is done, a humble offering of our talents and services in building the Lord's kingdom.

| Here am I, Thou great Creator;
| Here am I, O Lord, send me!
| Here am I to do Thy bidding:
| What I have I owe to Thee.
| Sould and body, Thou hast given
| All of mercy, full and free
| That for Thee I may employ them --
| Here am I, O Lord, send me!

| Here am I, my only Savior;
| Here am I, O Lord, send me!
| Thou hast wrought my full redemption
| By Thy death on Calvary.
| For my life Thy life was given
| On that barren, cursed tree
| That my life be spent in service --
| Here am I, O Lord, send me!

| Here am I, Thou Source of power,
| Here am I, O Lord, send me!
| Thou hast wrought, O Holy Spirit,
| Faith my Savior for to see
| By the comfort of Thy presence
| I have strength to live for Thee
| In a life of love and service --
| Here am I, O Lord, send me!

| Here am I, Thou Fount of Mercy;
| Here am I, O Lord, send me!
| Wheresoe'er Thy hand directs me
| I shall follow willingly.
| If but in the slightest measure
| I repay my debt to Thee,
| Then my life has not been wasted --
| Here am I, O Lord, send me!


