# Feed My Lambs! 
## John 21, 15 {.unlisted .unnumbered}
### Founding and Conducting a Sunday-School. {.unlisted .unnumbered}

The subject of this chapter is very closely connected with that of all personal endeavor in mission work.  It links up with the historical fact that the laymen of the early Church were actively engaged in spreading the Gospel, as we learned in Chapter 3, and that the Lord expects all Christians, whether pastors or laymen, to take a direct, personal, active interest in the spread of His kingdom.

The matter is brought home to us even by a consideration of some historical facts in church history.  The Methodist Church did not come into existence until a century after the establishment of the first Lutheran congregation in America.  And yet, this denomination has more than twice as many members in our country as all Lutheran bodies put together.  The Baptists began work in our country in 1636, or about the same time that Lutheran preaching was established on the Delaware.  Yet the Baptists, too, are much stronger than the combined Lutheran bodies of our country.

What is the explanation?  We cannot well speak of laxity in doctrine and life, for both bodies, at the time of their most rapid growth, were most conservative.  Moreover, some of their tenets might be considered unusually objectionable to the average person; for the Methodists had church rules which went beyond the Word of God in strictness, and the Baptists insisted upon immersion in baptism, a form which does not particularly commend itself to the average person. -- On the other hand, we know that the errors of these denominations were not the cause of their rapid growth, because the Holy Ghost does not operate through specific false teaching.

The explanation is to be found, at least in part, in the fact that the part of the truth which was stil held by these two church-bodies was spread with great zeal by laymen connected with these denominations.  And one of their chief agencies in establishing new churches and in doing Home Mission work was the Sunday-school, introduced to this country immediately after the War of the Revolution.  Wherever a Methodist or a Baptist settled, he tried to interest his neighbors in the establishment of a Sunday-school, and such a Sunday-school quickly became the nucleus of a congregation, for preaching was invariably introduced at the earliest opportunity.

This fact was brought home to the present writer in a very interesting and emphatic manner some years ago.  I was pastor in a Western city and also had charge of a small mission-station located in one of the suburbs.  This staition was visited every Sunday afternoon, and the only way to reach my destination was to take the street-car.  Now, I noticed that a number of young people invariably took the same car.  They were a cheerful group, but always carried on with a certain dignity.  They had Bibles and other religious literature with them, and they rode beyond my destination.  After some time I ventured to inquire where they were going and who they were.  I received the information very quickly.  They were members of one of the largest and richest churches in the city, and they went out every Sunday afternoon to conduct a Sunday-school in one of the small mining-towns to the northwest. 

I found out a few more facts, in the course of time.  One was this, that these young people, although, for the most part, sons and daughters of wealthy people, did not take their automobiles on these Sunday afternoon trips, lest the poor children whom they intended to serve be overawed by the splendor and have no confidence in them.  Besides, this group of young people were only one of nine sets of young people from the same church, all of whom conducted mission Sunday-schools in various suburbs of the city.

These facts gave me some food for thought, and I am only too glad to pass this information on to others.

ONE CHURCH WITH NINE MISSION SUNDAY-SCHOOLS, all of them conducted by young people, whose pastor was himself a mission-worker of note and managed to inspire his young people with the desire to do some real personal work for the Lord!

This is a possibility for church expansion which has been tried in our Church in only a few isolated instances.  But what a vista opens up before him who uses a little consecrated imagination together with a measure of common sense -- with 60 per cent. of our population unchurched, with approximately twenty million children growing up without any formal instruction in the truth of the Bible!

Here is work which consecrated young people (and old people) can undertake.  A small amount of training is now available for Sunday-school teachers, no matter where they are found.  Moreover, our pastors will be glad to conduct classes for the training of church-workers, as suggested in these pages.  And the literature for Sunday-school work is being published; it can easily be turned out in much greater quantities!

What can consecrated laymen, what can SOUL-WINNERS do in furthering the cause fo the Gospel and of the kingdom of God along these lines?

Let us remember, first of all, that _nothing should be undertaken where the work is already established_, where there is a congregation and a pastor within reasonable reach of any section of city or country.  In this case any unchurched people, young or old, will be reached through the systematic mission endeavor described in Chapters X and XI.

Let us remember, in the second place, that _work of this kind ought to be undertaken only under the auspices of the Church_.  Sometimes only one pastor is concerned, as when work is to be done in a suburb adjacent to a city where we have a church.  Sometimes a number of pastors and congregations will be interested, and in that case the local pastor will be glad to arrange for the work.  Sometimes a layman may become interested in mission-work in some city or town at a great distance from any of our congregations.  In that case it will be advisable, at least, to confer with the mission board of the District or have the local pastor take care of this formality.

The main thing is _that the work be done!_  And to this end a number of suggestions are here offered. 

When a field such as is described above is to be opened to the Church, an _exploration_ is in order.  If this is done by a careful canvass, it will yield the best survey of the field and give a picture of the possibilities, which can be shown in a graph.

The contact having been established by means of the canvass, the next step is to _enlist the aid of a sufficient number of volunteer workers_ to act as teachers and officers of the school, allowing a generous estimate of the people thus needed.  These people should be pledged, in fact, they ought to pledge themselves, to work for the success of the new missionary venture with all energy; for unless workers can be depended upon, all missionary efforts lack stability.

After the teaching staff has been provided for, the _territory itelf must be prepared_.  If the canvassers have been successful in their first endeavor, a list of prospective pupils may be made.  If there is a possibility of interesting at least some of the older people from the beginning, provisions for a Bible class should be made.

Next comes the _publicity work_.  A few days before the opening of the projected Sunday-school, the entire territory to be served should be covered with hand-bills, dodgers, and other forms of advertising.  If the local newspaper office does the printing, there may be a possibility of getting some space in the issue preceeding the Sunday of the opening.  Of course, personal invitations go to all who have signified their willingness to join the Sunday-school classes.

On the opening day the superintendent and all the teachers ought to be on hand in plenty of time in order that no delay may interfere with the organization of the school.  The children and all other attendands should be warmly, but not effusively, welcomed as they arrive, and, several registration desks having been provided, their names and addresses, their age, information concerning baptism (if available), brothers and sisters, possibly also church connection or confession of parents, should immediately be entered.  This must be done, of course, with proper kindness and tact.  Let the teachers and officers who are not engaged in the welcoming of the children and in their registration immediately engage the attention of those already enrolled by entering into a cheerful conversation with the children or showing them some Biblical pictures provided for the walls or for individual display.  Much information can be gained in this manner concerning the knowledge which the children possess in religious matters.  At the same time a tentative division into classes may be made, so that all the children will be in the care of their respective teachers when opening time comes or shortly after.

Having started with a familiar, cheerful hymn, the leader should address the assembled children, bidding them welcome once more and explaining the purpose of the school in a few simple sentences.  The regular lesson may then be taken up at once, for the children expect this and must not be disappointed.  Since, however, the first lesson will be largely in the nature of get-acquainted hour, the lesson will be brief, and much time may be given to singing.

Be sure to rehearse this opening so carefully, and to drill all officers so thoroughly, that everything will go forward without a hitch.  Very much depends on first impressions.  Remember that a Sunday-school is chiefly a mission-school, and while order and discipline must prevail, it must be guided with great tact and kindliness.  For this reason the devotional part of the service will also be planned with great care in order that all children may be impressed with the sacredness of the Word of God and with the privilege of taking part in lessons where it is taught.

For the organization of the Sunday-school itself and the manner in which it may best be conducted, see the pamphlet _The Lutheran Sunday-school_ published by Concordia Publishing House.

If the work thus begun is tactfully carried forward, so that at least some adults of the neighborhood become interested, it may not be long before regular services with preaching may be inaugurated.

Our goal is the establishment of a congregation with a Christial day-school and with all other institutions which make for the most effective church-work.

Do you realize in what spirit this work must be undertaken?

|	 I can do all things through Jesus, my Savior,
|	 Wherever He calls me to labor for Him;
|	 I can do all things, though all my endeavors
|	 Seem to lack energy, purpose, and vim.
|	 If He will call me, "Come, work in My vineyard!"
|	 If He assigns me the work I should do,
|	 Then I shall go, for whatever befalls me,
| 	 I in my faith must be steadfast and true.

|	 I can do all things through Jesus, my Savior,
|	 For in His blood my redemption is found;
|	 Often as sin and as weakness assail me
|	 He to His promise of mercy is bound;
|	 Knowing that nothing but wrath I do merit,
|	 Still for forgiveness I trustfully plead,
|	 Since in His righteousness lies my salvation
|	 If but His message of pardon I heed.

|	 I can do all things through Jesus, my Savior,
|	 Strong in the might from His power which flows,
|	 Clinging to Him as my Champion and Hero,
|	 Following on as my pathway He shows.
|	 Nothing can daunt or my confidence sever
|	 Nothing can part me from Jesus, my Lord;
|	 He will not leave me nor ever forsake me --
|	 That He has promised to me in His Word.

|	 I can do all things through Jesus, my Savior,
|	 Proud both and humble to follow His call;
|	 'Twas little children He took to His bosom
|	 'Twas little children He praised above all.
|	 If I can lead little children to Jesus,
|	 Teach them that in Him salvation they gain,
|	 Then I am happy, though humble my station,
|	 Then I am sure I have not lived in vain.

Thus we heed His injunction to
\begin{center} "FEED MY LAMBS" \end{center}


