---
title:  'While It Is Day!'
subtitle:  'A Manual for Soul-Winners'
author:  'Paul E. Kretzmann'
date:  '1926'
documentclass:  book
---

# While It Is Day.  John 9, 4 {.unlisted .unnumbered}

|	Let us work while it is day,
|	Let us labor while we may!
|	Soon will come the night of eath
|	When we yield our final breath.
|	Let us work for Chirst, the Lord,
|	Bear aloft His mighty Word!
|	
|	Let us work without restraint,
|	Never weary, lax or faint;
|	Firm in battling selfishness,
|	Loyal in true faithfulness,
|	Place our strength at His command,
|	Do His work throughout the land!
|	
|	Let us work while yet we may!
|	Soon will come that glorious day
|	When our labor here si done
|	When the precious prize is won,
|	When we rest and take our ease
|	In the homes of endless peace!
|	
|	(_Knowing and Doing_, p.82.)


# Foreword {.unnumbered}
In these days of spiritual and moral decay the question is often asked, "What's wrong with the church?"  And this question, while often presented by those who have never given the Church a fair trial, is, in a general way, warranted; for there is no institution in the entire world that can do so much good and has such high and holy responsibilities as the Church.  Where else shall the world turn, which is so torn by doubt and fear?  Where else, if not to the Church with its saving Gospel, the only message of hope?  Yes, the world is sick, and the Church has the only remedy that can cure its ills.

And in these days, when the Battle between Christianity and the world is becoming harder and harder and the line of demarcation separating the two is becoming more and more indistinct; when worldliness is making such terrible inroads in the Church; when love is becoming cold and indifference and laxity are paralyzing Christian activities; when, as the Savior predicted, there are all the indications that the world's destruction is near, -- in this our evil time, what does the Church itself need more than a deeper appreciation for the Gospel and a reconsecration to the spreading of this Gospel?  The need in our Church is not, primarily, more men and means, nor more churches and members, but congregations filled with a greater soul-winning spirit, members with a deeper passion for blood-bought souls, members, we repeat, who realize that an actually overwhelming responsibility rests upon them and that their sacred and supreme duty in this world is to testify for Christ by word and deed and thus to help save souls.

While we have heard it stated again and again -- and it is also brought out in this volume -- that two-thirds of the world, or nearly a thousand million souls, do not know Jesus, the Savior, we fail to work as determinedly and self-sacrificingly as we should to bring our fellow-sinners the tidings of salvation.  The great commission, "Go ye into all the world and preach the Gospel to every creature," often remains unfulfilled.  yet all our church- and school-work has this one object in view, this goal -- to help save souls.

Many and ever more soul-winners -- that is the need of the hour!  When our members have caught the soul-saving spirit, and when their hearts are set on fire to save men, greater advancements will be made in our mission-fields here and abroad.  There will be a larger outpouring of gifts, a self-sacrificing stewardship.  Our members will not be satisfied with giving merely part of their time, spare change, and to make half-hearted efforts, but they will give the best of their time, the best of their money, and put their whole heart and soul into the great work.  And there will be a solution to so many discouraging church problems.  The Church will grow inwardly and outwardly as never before.

Is it necessary to point out that our young people, the future leaders of the Church, should be in the very front ranks of the Church's missionary crusade?  Indeed, young and old should consider it the highest privilege to be colaborers with God in the work of salvation of men through Jesus Christ.  But our youth must lead.  In this spirit the leaders of the Walther League at the Detroit Convention proposed the so-called systematic mission endeavor.  This is merely a united and organized effort of the young people, under the direction of their pastors, to lead others to the Savior and His Church.  The plan was most whole-heartedly endorsed by succeeding conventions.  The endeavor, which is gaining in favor, has already wrought untold blessings for the Church in deepening the spirituality of the young people.

Realizing that the young people, while taking an active part, can only assist the pastors and congregations, the scope of _While It Is Day!_ was widened to be of direct use to all congregations of the entire Church and for all individual members, young and old.  It covers all practical phases; and where detailed information is not given, there are enough suggestions to help any judicious leader.  _While It Is Day!_ is also to serve as a text-book, and it is suggested that the various studies be taken up systematically in regular classes during six-to-eight-week periods.  The spirit of a united mission endeavor is well expressed in the title _While It Is Day!_  There is no time to be lost.  Every hour and every minute men are perishing without the saving Gospel.  "The night cometh when no man can work"; so let us labor "while it is day."

P.G. Prokopy


